type V=Record<string,string>;
function parse(input:string):V{try{return JSON.parse(input) as V}catch{return{}}}
const num=(v:V,k:string,d=0)=>{const n=Number(v[k]);return Number.isFinite(n)?n:d};
const lines=(s='')=>s.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
const round=(n:number,d=2)=>Number(n.toFixed(d));
const money=(n:number)=>round(n,2).toFixed(2);
const esc=(s='')=>s.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
function inches(value:number,unit:string){return unit==='mm'?value/25.4:unit==='cm'?value/2.54:value}
function meters(value:number,unit:string){return unit==='mm'?value/1000:unit==='cm'?value/100:value*.0254}
function sections(parts:[string,string|undefined][]) {return parts.filter(([,x])=>String(x||'').trim()).map(([k,x])=>`${k}:\n${String(x).trim()}`).join('\n\n')}
function json(data:unknown){return JSON.stringify(data,null,2)}
function stripHtml(html:string){if(typeof DOMParser!=='undefined'){const d=new DOMParser().parseFromString(html,'text/html');return d.body.textContent||''}return html.replace(/<[^>]+>/g,' ')}
function slugify(s:string){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function withUtm(raw:string,params:Record<string,string>){const u=new URL(raw);Object.entries(params).forEach(([k,val])=>{if(val)u.searchParams.set(k,val)});return u.toString()}
function commonPrompt(v:V){return sections([['Role',v.role],['Goal',v.goal],['Context',v.context],['Constraints',v.constraints],['Tone',v.tone],['Audience',v.audience],['Output format',v.output||v.format]])}

export function runExpansionTool(slug:string,category:string,input:string):string|undefined{
 const expansion=['ai','webseo','print','business','social'];
 if(!expansion.includes(category))return undefined;
 const v=parse(input);

 if(category==='ai'){
  if(slug==='prompt-builder')return commonPrompt(v);
  if(slug==='system-prompt-builder')return sections([['You are',v.role],['Rules',v.rules],['Context',v.context],['Response tone',v.tone],['Response format',v.output]]);
  if(['chatgpt-prompt-generator','social-media-prompt-generator','seo-prompt-generator','writing-prompt-generator'].includes(slug)){
    const flavor=slug.startsWith('social')?'Create social-media content':slug.startsWith('seo')?'Act as an SEO specialist':slug.startsWith('writing')?'Act as a professional writer':'Help me solve this task';
    return `${flavor}.\n\n${sections([['Topic',v.topic],['Audience',v.audience],['Objective',v.goal],['Tone',v.tone],['Format',v.format]])}`;
  }
  if(slug==='image-prompt-generator')return sections([['Subject',v.subject],['Scene',v.scene],['Visual style',v.style],['Lighting',v.lighting],['Camera / lens',v.camera],['Negative prompt',v.negative]]);
  if(slug==='logo-prompt-generator')return `Design a distinctive logo concept.\n\n${sections([['Brand',v.brand],['Industry',v.industry],['Brand values',v.values],['Desired style',v.style],['Color direction',v.colors],['Avoid',v.negative]])}`;
  if(slug==='product-photo-prompt-generator')return `Create a premium commercial product photograph.\n\n${sections([['Product',v.product],['Environment',v.scene],['Lighting',v.lighting],['Camera / lens',v.camera],['Style',v.style],['Background',v.background]])}`;
  if(slug==='coding-prompt-generator')return `Act as a senior software engineer.\n\n${sections([['Task',v.task],['Stack',v.stack],['Requirements',v.requirements],['Constraints',v.constraints],['Expected output',v.output]])}`;
  if(slug==='persona-prompt-generator')return `You are ${v.role || 'a specialized assistant'}${v.expertise?` with expertise in ${v.expertise}`:''}.\n\n${sections([['Tone',v.tone],['Operating rules',v.rules],['Boundaries',v.boundaries]])}`;
  if(slug==='negative-prompt-generator')return lines(v.negative).flatMap(x=>x.split(/[,;]+/)).map(x=>x.trim()).filter(Boolean).join(', ');
  if(slug==='prompt-to-json')return json({prompt:v.prompt,createdWith:'Controols',length:v.prompt?.length||0});
  if(slug==='json-to-prompt'){const data=JSON.parse(v.json);if(data&&typeof data==='object'&&!Array.isArray(data))return Object.entries(data).map(([k,x])=>`${k.replace(/[_-]/g,' ')}: ${typeof x==='object'?JSON.stringify(x):String(x)}`).join('\n');return String(data)}
  if(slug==='prompt-template-filler'){const vars=Object.fromEntries(lines(v.variables).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i).trim(),x.slice(i+1).trim()]}));return v.template.replace(/\{\{\s*([\w.-]+)\s*\}\}/g,(_,k)=>vars[k]??`{{${k}}}`)}
  if(slug==='prompt-variables-extractor'){const found=[...v.template.matchAll(/\{\{\s*([\w.-]+)\s*\}\}/g)].map(m=>m[1]);return [...new Set(found)].join('\n')}
  if(slug==='token-estimator'){const chars=v.text.length,cpt=Math.max(1,num(v,'charsPerToken',4)),tokens=Math.ceil(chars/cpt);return json({characters:chars,words:v.text.trim()?v.text.trim().split(/\s+/).length:0,estimatedTokens:tokens,assumption:`~${cpt} characters/token`})}
  if(slug==='context-window-estimator'){const chars=v.text.length,cpt=Math.max(1,num(v,'charsPerToken',4)),estimated=Math.ceil(chars/cpt),window=Math.max(1,num(v,'contextTokens',128000));return json({estimatedTokens:estimated,contextWindow:window,usagePercent:round(estimated/window*100,2),remainingTokens:Math.max(0,window-estimated),assumption:`~${cpt} characters/token`})}
 }

 if(category==='webseo'){
  if(slug==='meta-tags-generator')return `<title>${esc(v.title)}</title>\n<meta name="description" content="${esc(v.description)}">\n<link rel="canonical" href="${esc(v.url)}">\n<meta name="robots" content="index,follow">`;
  if(slug==='open-graph-generator')return [`<meta property="og:title" content="${esc(v.title)}">`,`<meta property="og:description" content="${esc(v.description)}">`,`<meta property="og:url" content="${esc(v.url)}">`,`<meta property="og:type" content="website">`,v.image?`<meta property="og:image" content="${esc(v.image)}">`:'',v.siteName?`<meta property="og:site_name" content="${esc(v.siteName)}">`:''].filter(Boolean).join('\n');
  if(slug==='twitter-card-generator')return [`<meta name="twitter:card" content="${v.image?'summary_large_image':'summary'}">`,`<meta name="twitter:title" content="${esc(v.title)}">`,`<meta name="twitter:description" content="${esc(v.description)}">`,v.image?`<meta name="twitter:image" content="${esc(v.image)}">`:''].filter(Boolean).join('\n');
  if(slug==='google-serp-preview')return `${v.title}\n${v.url}\n${v.description}\n\nTitle: ${v.title.length} chars · Description: ${v.description.length} chars`;
  if(slug==='social-share-preview')return `${v.title}\n${v.description}\n${v.url}${v.image?`\nImage: ${v.image}`:''}`;
  if(slug==='robots-txt-generator'){const out=[`User-agent: ${v.userAgent||'*'}`];lines(v.allow).forEach(x=>out.push(`Allow: ${x}`));lines(v.disallow).forEach(x=>out.push(`Disallow: ${x}`));if(v.sitemap)out.push('',`Sitemap: ${v.sitemap}`);return out.join('\n')}
  if(slug==='sitemap-url-list-generator'){const items=lines(v.urls).map(u=>`  <url>\n    <loc>${esc(u)}</loc>\n    <changefreq>${v.changefreq||'weekly'}</changefreq>\n    <priority>${v.priority||'0.8'}</priority>\n  </url>`).join('\n');return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${items}\n</urlset>`}
  if(slug==='canonical-tag-generator')return `<link rel="canonical" href="${esc(v.url)}">`;
  if(slug==='hreflang-generator'){const tags=lines(v.languages).map(x=>{const i=x.indexOf('=');if(i<1)return'';return `<link rel="alternate" hreflang="${esc(x.slice(0,i).trim())}" href="${esc(x.slice(i+1).trim())}">`}).filter(Boolean);if(v.defaultUrl)tags.push(`<link rel="alternate" hreflang="x-default" href="${esc(v.defaultUrl)}">`);return tags.join('\n')}
  if(slug==='utm-builder')return withUtm(v.url,{utm_source:v.source,utm_medium:v.medium,utm_campaign:v.campaign,utm_term:v.term,utm_content:v.content});
  if(slug==='url-parser'){const u=new URL(v.url);return json({protocol:u.protocol,host:u.host,hostname:u.hostname,port:u.port,pathname:u.pathname,search:u.search,hash:u.hash,query:Object.fromEntries(u.searchParams.entries())})}
  if(slug==='url-cleaner'){const u=new URL(v.url),tracking=['utm_source','utm_medium','utm_campaign','utm_term','utm_content','utm_id','gclid','fbclid','mc_cid','mc_eid','ref','ref_src'];tracking.forEach(k=>u.searchParams.delete(k));u.hash='';return u.toString()}
  if(slug==='query-parameter-remover'){const u=new URL(v.url);v.parameters.split(/[,;\s]+/).filter(Boolean).forEach(k=>u.searchParams.delete(k));return u.toString()}
  if(slug==='redirect-rule-generator'){const code=v.status||'301';return v.server==='nginx'?`location = ${v.source} {\n  return ${code} ${v.target};\n}`:`Redirect ${code} ${v.source} ${v.target}`}
  if(slug==='json-ld-website-generator'){const data:any={'@context':'https://schema.org','@type':'WebSite',name:v.name,url:v.url};if(v.searchUrl)data.potentialAction={'@type':'SearchAction',target:v.searchUrl,'query-input':'required name=search_term_string'};return `<script type="application/ld+json">\n${json(data)}\n</script>`}
  if(slug==='json-ld-organization-generator'){const data:any={'@context':'https://schema.org','@type':'Organization',name:v.name,url:v.url};if(v.logo)data.logo=v.logo;if(v.email)data.email=v.email;if(v.phone)data.telephone=v.phone;return `<script type="application/ld+json">\n${json(data)}\n</script>`}
  if(slug==='json-ld-local-business-generator'){const data:any={'@context':'https://schema.org','@type':'LocalBusiness',name:v.name,address:{'@type':'PostalAddress',streetAddress:v.address,addressLocality:v.city,addressRegion:v.region,addressCountry:v.country}};if(v.url)data.url=v.url;if(v.phone)data.telephone=v.phone;return `<script type="application/ld+json">\n${json(data)}\n</script>`}
  if(slug==='json-ld-product-generator'){const data:any={'@context':'https://schema.org','@type':'Product',name:v.name,offers:{'@type':'Offer',price:v.price,priceCurrency:v.currency||'BRL',availability:`https://schema.org/${v.availability||'InStock'}`}};if(v.description)data.description=v.description;if(v.sku)data.sku=v.sku;if(v.image)data.image=v.image;if(v.url)data.url=v.url;return `<script type="application/ld+json">\n${json(data)}\n</script>`}
  if(slug==='json-ld-faq-generator'){const qs=lines(v.questions),as=lines(v.answers),main=qs.map((q,i)=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:as[i]||''}}));return `<script type="application/ld+json">\n${json({'@context':'https://schema.org','@type':'FAQPage',mainEntity:main})}\n</script>`}
  if(slug==='html-heading-analyzer'){if(typeof DOMParser!=='undefined'){const d=new DOMParser().parseFromString(v.html,'text/html');const out=[...d.querySelectorAll('h1,h2,h3,h4,h5,h6')].map((el,i)=>({index:i+1,level:el.tagName.toLowerCase(),text:(el.textContent||'').trim()}));return json({count:out.length,headings:out})}return lines(v.html.match(/<h[1-6][^>]*>.*?<\/h[1-6]>/gis)?.join('\n')||'').join('\n')}
  if(slug==='meta-tag-analyzer'){if(typeof DOMParser!=='undefined'){const d=new DOMParser().parseFromString(v.html,'text/html');const get=(sel:string,attr='content')=>d.querySelector(sel)?.getAttribute(attr)||'';return json({title:d.querySelector('title')?.textContent||'',description:get('meta[name="description"]'),canonical:get('link[rel="canonical"]','href'),robots:get('meta[name="robots"]'),ogTitle:get('meta[property="og:title"]'),ogDescription:get('meta[property="og:description"]'),ogImage:get('meta[property="og:image"]')})}return 'HTML analysis requires a browser.'}
  if(slug==='link-extractor'){if(typeof DOMParser!=='undefined'){const d=new DOMParser().parseFromString(v.html,'text/html');return json([...d.querySelectorAll('a[href]')].map(a=>({text:(a.textContent||'').trim(),href:a.getAttribute('href')})))}return 'HTML analysis requires a browser.'}
  if(slug==='keyword-density-checker'){const plain=stripHtml(v.text).toLowerCase(),kw=v.keyword.trim().toLowerCase(),words=plain.match(/\p{L}[\p{L}\p{N}'’-]*/gu)||[],count=kw?plain.split(kw).length-1:0;return json({keyword:v.keyword,occurrences:count,totalWords:words.length,densityPercent:words.length?round(count/words.length*100,2):0})}
  if(slug==='html-title-description-length-checker')return json({title:{characters:v.title.length,status:v.title.length>=30&&v.title.length<=65?'good':'review'},description:{characters:v.description.length,status:v.description.length>=70&&v.description.length<=170?'good':'review'}})
 }

 if(category==='print'){
  if(slug==='bleed-calculator'){const w=num(v,'width'),h=num(v,'height'),b=num(v,'bleed');return json({final:`${w} × ${h} ${v.unit}`,artworkWithBleed:`${round(w+2*b)} × ${round(h+2*b)} ${v.unit}`,bleedEachSide:`${b} ${v.unit}`})}
  if(slug==='safe-margin-calculator'){const w=num(v,'width'),h=num(v,'height'),m=num(v,'margin');return json({final:`${w} × ${h} ${v.unit}`,safeArea:`${round(Math.max(0,w-2*m))} × ${round(Math.max(0,h-2*m))} ${v.unit}`,marginEachSide:`${m} ${v.unit}`})}
  if(['print-dpi-calculator','effective-print-dpi-calculator'].includes(slug)){const dx=num(v,'pixelWidth')/inches(num(v,'printWidth'),v.unit),dy=num(v,'pixelHeight')/inches(num(v,'printHeight'),v.unit),avg=(dx+dy)/2;const result:any={horizontalDpi:round(dx,1),verticalDpi:round(dy,1),averageDpi:round(avg,1)};if(slug==='print-dpi-calculator')result.recommendation=avg>=300?'Excellent for close-view print':avg>=200?'Good for most print':avg>=120?'Acceptable for larger viewing distance':'Low resolution for the requested size';return json(result)}
  if(['max-print-size-calculator','pixels-to-print-size'].includes(slug)){const dpi=Math.max(1,num(v,'dpi')),wi=num(v,'pixelWidth')/dpi,hi=num(v,'pixelHeight')/dpi;return json({inches:`${round(wi)} × ${round(hi)} in`,centimeters:`${round(wi*2.54)} × ${round(hi*2.54)} cm`,millimeters:`${round(wi*25.4)} × ${round(hi*25.4)} mm`,dpi})}
  if(slug==='print-size-to-pixels'){const dpi=Math.max(1,num(v,'dpi')),w=Math.round(inches(num(v,'width'),v.unit)*dpi),h=Math.round(inches(num(v,'height'),v.unit)*dpi);return json({requiredPixels:`${w} × ${h} px`,dpi})}
  if(slug==='banner-scale-calculator'){const scale=Math.max(1,num(v,'scale',10));return json({real:`${v.width} × ${v.height} ${v.unit}`,artwork:`${round(num(v,'width')/scale)} × ${round(num(v,'height')/scale)} ${v.unit}`,scale:`1:${scale}`})}
  if(['scale-1-to-10-calculator','scale-1-to-20-calculator'].includes(slug)){const d=slug.includes('10')?10:20;return json({real:`${v.width} × ${v.height} ${v.unit}`,artwork:`${round(num(v,'width')/d)} × ${round(num(v,'height')/d)} ${v.unit}`,scale:`1:${d}`})}
  if(slug==='square-meter-price-calculator'){const area=meters(num(v,'width'),v.unit)*meters(num(v,'height'),v.unit),total=area*num(v,'priceM2');return json({areaSquareMeters:round(area,4),pricePerSquareMeter:money(num(v,'priceM2')),total:money(total)})}
  if(slug==='sticker-cost-calculator'){const one=meters(num(v,'itemWidth'),v.unit)*meters(num(v,'itemHeight'),v.unit),qty=Math.max(1,num(v,'quantity')),area=one*qty,total=area*num(v,'priceM2');return json({areaPerStickerM2:round(one,6),totalAreaM2:round(area,4),materialCost:money(total),costPerSticker:money(total/qty)})}
  if(['units-per-sheet-calculator','sheet-imposition-calculator'].includes(slug)){const sw=num(v,'sheetWidth'),sh=num(v,'sheetHeight'),iw=num(v,'itemWidth'),ih=num(v,'itemHeight'),g=num(v,'gap');const fit=(W:number,H:number,w:number,h:number)=>Math.max(0,Math.floor((W+g)/(w+g)))*Math.max(0,Math.floor((H+g)/(h+g)));const normal=fit(sw,sh,iw,ih),rotated=fit(sw,sh,ih,iw),per=Math.max(normal,rotated);const result:any={normalOrientation:normal,rotatedOrientation:rotated,bestPerSheet:per,bestOrientation:rotated>normal?'rotated':'normal'};if(slug==='sheet-imposition-calculator'){const qty=Math.max(1,num(v,'quantity'));result.quantity=qty;result.sheetsNeeded=per?Math.ceil(qty/per):0;result.extraCapacity=per?Math.ceil(qty/per)*per-qty:0}return json(result)}
  if(slug==='paper-size-calculator-pro'){const sizes:Record<string,[number,number]>={A0:[841,1189],A1:[594,841],A2:[420,594],A3:[297,420],A4:[210,297],A5:[148,210],SRA3:[320,450]};const [w,h]=sizes[v.paper]||sizes.A4,scale=Math.max(.01,num(v,'scale',1));return json({paper:v.paper,actualMm:`${w} × ${h}`,scaledMm:`${round(w/scale)} × ${round(h/scale)}`,scale:scale===1?'1:1':`1:${scale}`})}
  if(slug==='aspect-ratio-for-print'){const a=num(v,'artWidth')/num(v,'artHeight'),p=num(v,'printWidth')/num(v,'printHeight'),diff=Math.abs(a-p)/p*100;return json({artRatio:round(a,4),printRatio:round(p,4),differencePercent:round(diff,2),fit:diff<.5?'match':diff<3?'minor crop likely':'crop or empty space likely'})}
  if(slug==='rgb-cmyk-estimator'){const r=num(v,'red')/255,g=num(v,'green')/255,b=num(v,'blue')/255,k=1-Math.max(r,g,b);const c=k===1?0:(1-r-k)/(1-k),m=k===1?0:(1-g-k)/(1-k),y=k===1?0:(1-b-k)/(1-k);return json({C:round(c*100,1),M:round(m*100,1),Y:round(y*100,1),K:round(k*100,1),note:'Approximate conversion; print profiles can produce different values.'})}
  if(slug==='print-quantity-price-calculator'){const q=Math.max(1,num(v,'quantity')),cost=num(v,'unitCost')*q,total=cost*(1+num(v,'markup')/100);return json({quantity:q,totalCost:money(cost),suggestedTotal:money(total),suggestedUnitPrice:money(total/q),markupPercent:num(v,'markup')})}
 }

 if(category==='business'){
  if(slug==='selling-price-calculator'){const c=num(v,'totalCost'),m=num(v,'margin');const price=m>=100?Infinity:c/(1-m/100);return json({cost:money(c),desiredMarginPercent:m,sellingPrice:Number.isFinite(price)?money(price):'invalid',profit:Number.isFinite(price)?money(price-c):'invalid'})}
  if(slug==='hourly-rate-calculator'){const needed=num(v,'monthlyIncome')+num(v,'monthlyCosts'),h=Math.max(1,num(v,'billableHours'));return json({monthlyTarget:money(needed),billableHours:h,suggestedHourlyRate:money(needed/h)})}
  if(slug==='freelance-project-price-calculator'){const base=num(v,'hours')*num(v,'hourlyRate')+num(v,'expenses'),total=base*(1+num(v,'contingency')/100);return json({labor:money(num(v,'hours')*num(v,'hourlyRate')),expenses:money(num(v,'expenses')),base:money(base),contingencyPercent:num(v,'contingency'),suggestedPrice:money(total)})}
  if(slug==='cost-per-unit-calculator')return json({totalCost:money(num(v,'totalCost')),quantity:num(v,'quantity'),costPerUnit:money(num(v,'totalCost')/Math.max(1,num(v,'quantity')))})
  if(slug==='commission-calculator'){const p=num(v,'price'),c=p*num(v,'commission')/100;return json({gross:money(p),commission:money(c),net:money(p-c)})}
  if(slug==='sales-goal-calculator'){const n=Math.ceil(num(v,'revenueGoal')/Math.max(.0001,num(v,'averageSale')));return json({revenueGoal:money(num(v,'revenueGoal')),averageSale:money(num(v,'averageSale')),salesNeeded:n})}
  if(slug==='break-even-calculator'){const margin=num(v,'price')-num(v,'variableCost'),units=margin>0?Math.ceil(num(v,'fixedCosts')/margin):0;return json({contributionPerUnit:money(margin),breakEvenUnits:units,breakEvenRevenue:money(units*num(v,'price'))})}
  if(slug==='roi-calculator'){const inv=num(v,'investment'),ret=num(v,'returnValue');return json({investment:money(inv),returnValue:money(ret),profit:money(ret-inv),roiPercent:round((ret-inv)/inv*100,2)})}
  if(slug==='cac-calculator')return json({spend:money(num(v,'marketingSpend')),newCustomers:num(v,'newCustomers'),cac:money(num(v,'marketingSpend')/Math.max(1,num(v,'newCustomers')))})
  if(slug==='ltv-calculator'){const ltv=num(v,'averageTicket')*num(v,'purchaseFrequency')*num(v,'retention');return json({averageTicket:money(num(v,'averageTicket')),purchaseFrequency:num(v,'purchaseFrequency'),retentionPeriods:num(v,'retention'),estimatedLtv:money(ltv)})}
  if(slug==='ltv-cac-ratio-calculator'){const ratio=num(v,'ltv')/Math.max(.0001,num(v,'cac'));return json({ltv:money(num(v,'ltv')),cac:money(num(v,'cac')),ratio:round(ratio,2),display:`${round(ratio,2)}:1`})}
  if(slug==='contribution-margin-calculator'){const cm=num(v,'price')-num(v,'variableCosts');return json({contributionMargin:money(cm),contributionMarginPercent:num(v,'price')?round(cm/num(v,'price')*100,2):0})}
  if(slug==='fixed-variable-cost-calculator'){const total=num(v,'fixedCosts')+num(v,'variableCosts');return json({fixedCosts:money(num(v,'fixedCosts')),variableCosts:money(num(v,'variableCosts')),totalCosts:money(total),fixedSharePercent:total?round(num(v,'fixedCosts')/total*100,2):0})}
  if(slug==='payroll-cost-estimator'){const salary=num(v,'salary'),total=salary*(1+num(v,'charges')/100);return json({salary:money(salary),chargesPercent:num(v,'charges'),estimatedCharges:money(total-salary),estimatedTotalCost:money(total)})}
  if(slug==='monthly-to-hourly-salary')return json({monthly:money(num(v,'salary')),hours:num(v,'workHours'),hourly:money(num(v,'salary')/Math.max(1,num(v,'workHours')))})
  if(slug==='hourly-to-monthly-salary')return json({hourly:money(num(v,'hourlyRate')),hours:num(v,'workHours'),monthly:money(num(v,'hourlyRate')*num(v,'workHours'))})
  if(slug==='revenue-growth-calculator'){const old=num(v,'oldRevenue'),nw=num(v,'newRevenue'),change=nw-old;return json({previous:money(old),current:money(nw),absoluteChange:money(change),growthPercent:old?round(change/old*100,2):null})}
  if(slug==='cash-discount-vs-installments'){const cash=num(v,'cashPrice'),inst=num(v,'installmentTotal'),diff=inst-cash;return json({cash:money(cash),installmentsTotal:money(inst),difference:money(diff),cashSavingsPercent:inst?round(diff/inst*100,2):0,cheaper:cash<inst?'cash':cash>inst?'installments':'same nominal total'})}
 }

 if(category==='social'){
  if(slug==='instagram-carousel-split-planner'){const cards=Math.max(2,Math.round(num(v,'cards',7))),w=Math.round(num(v,'cardWidth',1080)),h=Math.round(num(v,'cardHeight',1350));return json({cards,canvas:`${cards*w} × ${h} px`,eachCard:`${w} × ${h} px`,cuts:Array.from({length:cards-1},(_,i)=>(i+1)*w)})}
  if(slug==='social-image-size-guide'){const map:Record<string,Record<string,string>>={instagram:{feed:'1080 × 1350 px (4:5)',story:'1080 × 1920 px (9:16)',cover:'1080 × 1920 px; keep key content centered',profile:'320 × 320 px'},youtube:{feed:'1280 × 720 px',story:'1080 × 1920 px',cover:'1280 × 720 px thumbnail',profile:'800 × 800 px'},tiktok:{feed:'1080 × 1920 px',story:'1080 × 1920 px',cover:'1080 × 1920 px',profile:'200 × 200 px'},facebook:{feed:'1200 × 1500 px',story:'1080 × 1920 px',cover:'851 × 315 px',profile:'320 × 320 px'},linkedin:{feed:'1200 × 1500 px',story:'1080 × 1920 px',cover:'1584 × 396 px',profile:'400 × 400 px'},x:{feed:'1600 × 900 px',story:'1080 × 1920 px',cover:'1500 × 500 px',profile:'400 × 400 px'}};return `${v.platform}: ${map[v.platform]?.[v.format]||'Check the latest platform documentation for this format.'}`}
  if(slug==='instagram-caption-formatter')return v.text.replace(/\r/g,'').split(/\n{2,}/).map(p=>p.split(/\n/).map(x=>x.trim()).filter(Boolean).join(' ')).filter(Boolean).join('\n\n').replace(/[ \t]{2,}/g,' ')
  if(slug==='hashtag-cleaner'){const tags=v.text.match(/#[\p{L}\p{N}_]+/gu)||v.text.split(/[\s,;]+/).filter(Boolean).map(x=>x.startsWith('#')?x:`#${x}`);return [...new Set(tags.map(x=>`#${slugify(x.replace(/^#/,'')) .replace(/-/g,'')}`).filter(x=>x.length>1))].join(' ')}
  if(slug==='hashtag-counter'){const tags=v.text.match(/#[\p{L}\p{N}_]+/gu)||[];const unique=[...new Set(tags.map(x=>x.toLowerCase()))];return json({total:tags.length,unique:unique.length,repeated:tags.length-unique.length,hashtags:unique})}
  if(['bio-character-counter','youtube-title-counter','tiktok-caption-counter','x-post-counter'].includes(slug)){const limit=Math.max(1,num(v,'limit')),chars=[...v.text].length;return json({characters:chars,limit,remaining:limit-chars,status:chars<=limit?'within limit':'over limit'})}
  if(slug==='youtube-description-counter'||slug==='linkedin-post-counter'){const chars=[...v.text].length,words=v.text.trim()?v.text.trim().split(/\s+/).length:0;return json({characters:chars,words,lines:v.text.split(/\r?\n/).length})}
  if(slug==='social-link-utm-builder')return withUtm(v.url,{utm_source:v.platform||'social',utm_medium:'social',utm_campaign:v.campaign,utm_content:v.content});
  if(slug==='content-calendar-generator'){const themes=lines(v.themes),count=Math.max(1,Math.round(num(v,'posts',12))),start=new Date(`${v.startDate}T12:00:00`),items=Array.from({length:count},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i*2);return{date:d.toISOString().slice(0,10),platform:v.platform||'social',theme:themes[i%Math.max(1,themes.length)]||`Content ${i+1}`}});return json(items)}
  if(slug==='content-brief-generator')return sections([['Topic',v.topic],['Audience',v.audience],['Objective',v.goal],['Main message',v.message],['Call to action',v.action]])
  if(slug==='reel-hook-generator'){const topic=v.topic,a=v.audience?` for ${v.audience}`:'';return [`What nobody tells you about ${topic}${a}.`,`Before you try ${topic}, know this.`,`3 mistakes people make with ${topic}.`,`If ${topic} feels difficult, start here.`,`The fastest way to understand ${topic}.`,`Stop doing this when it comes to ${topic}.`,`A simple change that improves ${topic}.`].join('\n')}
  if(slug==='call-to-action-generator'){return [`Discover ${v.offer} — ${v.action}.`,`Ready for ${v.offer}? ${v.action}.`,`Take the next step with ${v.offer}. ${v.action}.`,`Want to make this easier? ${v.action}.`,`Start with ${v.offer} today — ${v.action}.`].join('\n')}
  if(slug==='social-media-brief-generator')return sections([['Brand',v.brand],['Goal',v.goal],['Audience',v.audience],['Channels',v.channels],['Main message',v.message]])
  if(slug==='carousel-outline-generator'){const count=Math.max(2,Math.round(num(v,'cards',7))),slides=Array.from({length:count},(_,i)=>i===0?`1. Cover — ${v.topic}`:i===count-1?`${i+1}. Closing / CTA — next step for ${v.topic}`:`${i+1}. Key point ${i} about ${v.topic}`);return slides.join('\n')}
 }
 return undefined;
}
