function nums(input:string){return input.split(/[;,\s]+/).map(Number).filter(Number.isFinite)}
function tidy(n:number){return Number.isFinite(n)?String(Number(n.toFixed(10))):'Invalid result'}
function randomBytes(n:number){const a=new Uint8Array(n);crypto.getRandomValues(a);return a}
function hex(bytes:Uint8Array){return [...bytes].map(b=>b.toString(16).padStart(2,'0')).join('')}
function b64(bytes:Uint8Array){return btoa(String.fromCharCode(...bytes))}
function fromB64(s:string){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function parseColor(input:string){const s=input.trim();if(/^#?[0-9a-f]{6}$/i.test(s)){const h=s.replace('#','');return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)] as const}const n=nums(s);return [n[0]||0,n[1]||0,n[2]||0] as const}
function rgbHex(r:number,g:number,b:number){return '#'+[r,g,b].map(v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,'0')).join('').toUpperCase()}
function rgbHsl(r:number,g:number,b:number){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),l=(max+min)/2,d=max-min;let h=0,s=0;if(d){s=l>.5?d/(2-max-min):d/(max+min);if(max===r)h=(g-b)/d+(g<b?6:0);else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h/=6}return [h*360,s*100,l*100]}
function hslRgb(h:number,s:number,l:number){h=((h%360)+360)%360/360;s/=100;l/=100;if(!s){const v=l*255;return [v,v,v] as const}const f=(p:number,q:number,t:number)=>{if(t<0)t+=1;if(t>1)t-=1;if(t<1/6)return p+(q-p)*6*t;if(t<1/2)return q;if(t<2/3)return p+(q-p)*(2/3-t)*6;return p};const q=l<.5?l*(1+s):l+s-l*s,p=2*l-q;return [f(p,q,h+1/3)*255,f(p,q,h)*255,f(p,q,h-1/3)*255] as const}
function lum(rgb:readonly number[]){const c=rgb.map(v=>{v/=255;return v<=.03928?v/12.92:Math.pow((v+.055)/1.055,2.4)});return .2126*c[0]+.7152*c[1]+.0722*c[2]}

export function runDesign(slug:string,input:string){const [r,g,b]=parseColor(input),hsl=rgbHsl(r,g,b);switch(slug){
case'hex-to-rgb':return`${r}, ${g}, ${b}`;case'rgb-to-hex':return rgbHex(r,g,b);case'hex-to-hsl':case'rgb-to-hsl':return`${tidy(hsl[0])}, ${tidy(hsl[1])}%, ${tidy(hsl[2])}%`;case'hsl-to-rgb':{const n=nums(input),x=hslRgb(n[0],n[1],n[2]);return x.map(Math.round).join(', ')}case'hsl-to-hex':{const n=nums(input),x=hslRgb(n[0],n[1],n[2]);return rgbHex(x[0],x[1],x[2])}case'hex-to-cmyk':{const R=r/255,G=g/255,B=b/255,K=1-Math.max(R,G,B);if(K===1)return'0, 0, 0, 100';return`${tidy((1-R-K)/(1-K)*100)}, ${tidy((1-G-K)/(1-K)*100)}, ${tidy((1-B-K)/(1-K)*100)}, ${tidy(K*100)}`}case'cmyk-to-hex':{const [c,m,y,k]=nums(input).map(x=>x/100);return rgbHex(255*(1-c)*(1-k),255*(1-m)*(1-k),255*(1-y)*(1-k))}case'color-contrast-checker':case'wcag-contrast-ratio':{const [a,z]=input.split('|');const A=lum(parseColor(a||'#000')),B=lum(parseColor(z||'#fff'));return tidy((Math.max(A,B)+.05)/(Math.min(A,B)+.05))}case'complementary-color':return rgbHex(255-r,255-g,255-b);case'analogous-colors':return[-30,0,30].map(d=>{const x=hslRgb(hsl[0]+d,hsl[1],hsl[2]);return rgbHex(x[0],x[1],x[2])}).join(', ');case'triadic-colors':return[0,120,240].map(d=>{const x=hslRgb(hsl[0]+d,hsl[1],hsl[2]);return rgbHex(x[0],x[1],x[2])}).join(', ');case'tetradic-colors':return[0,90,180,270].map(d=>{const x=hslRgb(hsl[0]+d,hsl[1],hsl[2]);return rgbHex(x[0],x[1],x[2])}).join(', ');case'color-shades-generator':return[20,35,50,65,80].map(l=>{const x=hslRgb(hsl[0],hsl[1],l);return rgbHex(x[0],x[1],x[2])}).join(', ');case'color-tints-generator':return[.15,.3,.45,.6,.75].map(x=>rgbHex(r+(255-r)*x,g+(255-g)*x,b+(255-b)*x)).join(', ');case'random-color-generator':{const x=randomBytes(3);return rgbHex(x[0],x[1],x[2])}case'gradient-generator':{const[a='#111827',z='#22c55e']=input.split('|');return`linear-gradient(135deg, ${a.trim()}, ${z.trim()})`}case'css-box-shadow-generator':return`0 12px 30px ${input||'rgba(0,0,0,.18)'}`;case'css-text-shadow-generator':return`0 2px 8px ${input||'rgba(0,0,0,.25)'}`;case'border-radius-generator':return`${Number(input)||16}px`;case'css-filter-generator':return`brightness(${Number(input)||100}%) contrast(100%) saturate(100%)`;case'opacity-color-generator':return`rgba(${r}, ${g}, ${b}, ${nums(input)[3]??.5})`;case'aspect-ratio-calculator':{const n=nums(input);return tidy(n[0]/n[1])}case'px-to-rem':return tidy((Number(input)||0)/16)+'rem';case'rem-to-px':return tidy((Number(input)||0)*16)+'px';case'px-to-cm':return tidy((Number(input)||0)*2.54/96)+'cm';case'cm-to-px':return tidy((Number(input)||0)*96/2.54)+'px';case'print-size-calculator':{const n=nums(input);return`${tidy(n[0]/(n[2]||300)*2.54)} × ${tidy(n[1]/(n[2]||300)*2.54)} cm`}case'dpi-calculator':{const n=nums(input);return tidy(n[0]/(n[1]/2.54))+' DPI'}}return input}

const tables:Record<string,Record<string,number>>={length:{m:1,km:1000,cm:.01,mm:.001,mi:1609.344,yd:.9144,ft:.3048,in:.0254},area:{m2:1,km2:1e6,cm2:1e-4,ha:1e4,acre:4046.8564224,ft2:.09290304},volume:{l:1,ml:.001,m3:1000,gal:3.785411784,cup:.2365882365,tbsp:.0147867648,tsp:.0049289216},mass:{kg:1,g:.001,mg:1e-6,lb:.45359237,oz:.028349523125,t:1000},speed:{'m/s':1,'km/h':1/3.6,mph:.44704,knot:.514444},pressure:{pa:1,kpa:1000,bar:1e5,psi:6894.757293,atm:101325},energy:{j:1,kj:1000,cal:4.184,kcal:4184,kwh:3.6e6},power:{w:1,kw:1000,hp:745.699872},time:{s:1,min:60,h:3600,day:86400,week:604800},angle:{rad:1,deg:Math.PI/180,grad:Math.PI/200},'data-size':{b:1,kb:1024,mb:1048576,gb:1073741824,tb:1099511627776},frequency:{hz:1,khz:1e3,mhz:1e6,ghz:1e9},torque:{nm:1,lbft:1.3558179483},acceleration:{'m/s2':1,'ft/s2':.3048,g:9.80665},density:{'kg/m3':1,'g/cm3':1000},force:{n:1,kn:1000,lbf:4.4482216153},'electric-current':{a:1,ma:.001,ua:1e-6},voltage:{v:1,mv:.001,kv:1000},resistance:{ohm:1,kohm:1000,mohm:1e6},capacitance:{f:1,mf:1e-3,uf:1e-6,nf:1e-9,pf:1e-12},inductance:{h:1,mh:1e-3,uh:1e-6},luminance:{'cd/m2':1,nit:1},illuminance:{lux:1,fc:10.7639104},'flow-rate':{'l/s':1,'l/min':1/60,'m3/h':1000/3600,gpm:3.785411784/60},'digital-transfer-rate':{'b/s':1,'kb/s':1e3,'mb/s':1e6,'gb/s':1e9},'typography-unit':{px:1,pt:96/72,pc:16,rem:16,em:16},'cooking-volume':{ml:1,l:1000,cup:236.588,tbsp:14.7868,tsp:4.92892},'cooking-weight':{g:1,kg:1000,oz:28.3495,lb:453.592},'screen-size':{in:1,cm:1/2.54,mm:1/25.4},'astronomical-distance':{km:1,au:149597870.7,ly:9.460730472e12,pc:3.085677581e13}}
export function runUnit(slug:string,input:string){const p=input.trim().split(/\s+/),v=Number(p[0]),from=(p[1]||'').toLowerCase(),to=(p[2]||'').toLowerCase();if(slug==='temperature-converter'){let c=from==='f'?(v-32)*5/9:from==='k'?v-273.15:v;return tidy(to==='f'?c*9/5+32:to==='k'?c+273.15:c)}if(slug==='fuel-economy-converter'){if(from==='l/100km'&&to==='mpg')return tidy(235.214583/v);if(from==='mpg'&&to==='l/100km')return tidy(235.214583/v)}if(slug==='shoe-size-converter'){const eu=v;return to==='us'?tidy(eu-33):to==='uk'?tidy(eu-34):tidy(eu)}if(slug==='clothing-size-converter'){const sizes=['XS','S','M','L','XL','XXL'];const i=Math.max(0,Math.min(5,Math.round(v)));return sizes[i]}if(slug==='paper-size-converter'){const paper:Record<string,string>={a0:'841 × 1189 mm',a1:'594 × 841 mm',a2:'420 × 594 mm',a3:'297 × 420 mm',a4:'210 × 297 mm',a5:'148 × 210 mm',letter:'216 × 279 mm',legal:'216 × 356 mm'};return paper[from]||'Use: A4'}const key=slug.replace('-converter',''),t=tables[key];if(t&&t[from]!=null&&t[to]!=null)return tidy(v*t[from]/t[to]);return'Format: value from to — example: 10 km mi'}

function base32Encode(bytes:Uint8Array){const a='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,val=0,out='';for(const b of bytes){val=(val<<8)|b;bits+=8;while(bits>=5){out+=a[(val>>(bits-5))&31];bits-=5}}if(bits)out+=a[(val<<(5-bits))&31];return out}
function base32Decode(s:string){const a='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,val=0;const out:number[]=[];for(const c of s.toUpperCase().replace(/=|\s/g,'')){const x=a.indexOf(c);if(x<0)continue;val=(val<<5)|x;bits+=5;if(bits>=8){out.push((val>>(bits-8))&255);bits-=8}}return new Uint8Array(out)}
async function aesKey(password:string){return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode(password)),{name:'AES-GCM'},false,['encrypt','decrypt'])}
export async function runSecurity(slug:string,input:string){if(/^sha(1|256|384|512)-hash-generator$/.test(slug)||slug==='file-sha256-checksum'){const alg=slug==='file-sha256-checksum'?'SHA-256':({'1':'SHA-1','256':'SHA-256','384':'SHA-384','512':'SHA-512'} as Record<string,string>)[slug.match(/^sha(1|256|384|512)/)![1]];return hex(new Uint8Array(await crypto.subtle.digest(alg,new TextEncoder().encode(input))))}switch(slug){case'random-password-generator':{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*';return[...randomBytes(Math.max(8,Math.min(128,Number(input)||20)))].map(x=>chars[x%chars.length]).join('')}case'passphrase-generator':{const l=['river','orbit','copper','forest','pixel','amber','cloud','tiger','nova','stone','mint','echo','solar','drift','maple','ocean'];return[...randomBytes(Number(input)||5)].map(x=>l[x%l.length]).join('-')}case'secure-random-number':{const n=new Uint32Array(1);crypto.getRandomValues(n);return String(n[0])}case'secure-random-string':return b64(randomBytes(Number(input)||24));case'password-strength-checker':{let s=0;if(input.length>=12)s++;if(/[a-z]/.test(input)&&/[A-Z]/.test(input))s++;if(/\d/.test(input))s++;if(/[^\w]/.test(input))s++;return['Very weak','Weak','Fair','Strong','Very strong'][s]}case'uuid-v4-generator':return crypto.randomUUID();case'random-token-generator':return b64(randomBytes(32)).replace(/=+$/,'');case'random-api-key-generator':return'ct_'+b64(randomBytes(32)).replace(/=+$/,'');case'hmac-sha256-generator':{const[k,m]=input.split('|||');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(k||''),{name:'HMAC',hash:'SHA-256'},false,['sign']);return hex(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(m||''))))}case'aes-encrypt-text':{const[p,m]=input.split('|||'),iv=randomBytes(12),key=await aesKey(p||'controols'),enc=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(m||'')));return b64(iv)+'.'+b64(enc)}case'aes-decrypt-text':{const[p,bundle]=input.split('|||'),[ivs,data]=String(bundle||'').split('.'),iv=fromB64(ivs),key=await aesKey(p||'controols'),dec=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,fromB64(data));return new TextDecoder().decode(dec)}case'base32-encode':return base32Encode(new TextEncoder().encode(input));case'base32-decode':return new TextDecoder().decode(base32Decode(input));case'totp-secret-generator':return base32Encode(randomBytes(20));case'string-entropy-calculator':return tidy(input.length*Math.log2(Math.max(1,new Set(input).size)))+' bits'}return''}

function hav(a:number,b:number,c:number,d:number){const R=6371,r=(x:number)=>x*Math.PI/180,q=Math.sin(r(c-a)/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(r(d-b)/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
export function runGeo(slug:string,input:string){const n=nums(input),[a=0,b=0,c=0,d=0]=n;switch(slug){case'distance-between-coordinates':case'haversine-distance-calculator':return tidy(hav(a,b,c,d))+' km';case'bearing-calculator':{const r=(x:number)=>x*Math.PI/180,deg=(x:number)=>x*180/Math.PI,y=Math.sin(r(d-b))*Math.cos(r(c)),x=Math.cos(r(a))*Math.sin(r(c))-Math.sin(r(a))*Math.cos(r(c))*Math.cos(r(d-b));return tidy((deg(Math.atan2(y,x))+360)%360)+'°'}case'midpoint-calculator':return`${tidy((a+c)/2)}, ${tidy((b+d)/2)}`;case'latitude-longitude-parser':return JSON.stringify({latitude:a,longitude:b},null,2);case'decimal-degrees-to-dms':return`${Math.floor(Math.abs(a))}° ${Math.floor((Math.abs(a)%1)*60)}' ${tidy((((Math.abs(a)%1)*60)%1)*60)}\"`;case'dms-to-decimal-degrees':return tidy(a+b/60+c/3600);case'gps-coordinate-validator':return String(a>=-90&&a<=90&&b>=-180&&b<=180);case'map-bounding-box-calculator':return JSON.stringify({south:Math.min(a,c),west:Math.min(b,d),north:Math.max(a,c),east:Math.max(b,d)},null,2);case'circle-radius-area-calculator':return tidy(Math.PI*a*a)+' km²';case'speed-from-distance-time':return tidy(a/b)+' km/h';case'travel-time-calculator':return tidy(a/b)+' h';case'coordinate-rounder':return`${a.toFixed(c||5)}, ${b.toFixed(c||5)}`;case'geojson-point-generator':return JSON.stringify({type:'Point',coordinates:[b,a]},null,2);case'geojson-bounding-box-generator':return JSON.stringify({type:'Polygon',coordinates:[[[b,a],[d,a],[d,c],[b,c],[b,a]]]},null,2)}return''}
