import type { CardDefinition } from "../../domain";

export const SET001_RAGE: readonly CardDefinition[] = [
  {
    id: "SET001-0001",
    setId: "SET001",
    collectorNumber: 1,
    name: "Faísca Kira",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "COMMON",
    cost: 1,
    attack: 2,
    defense: 1,
    rulesText: "",
    archetypes: ["Pressão rápida"],
  },
  {
    id: "SET001-0002",
    setId: "SET001",
    collectorNumber: 2,
    name: "Chassi Quente",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "COMMON",
    cost: 1,
    attack: 1,
    defense: 2,
    rulesText: "Na primeira vez em que sofrer dano e sobreviver a cada turno, recebe +1 ATQ até o fim do turno.",
    archetypes: ["Dano próprio"],
    effects: [
      { trigger: "PASSIVE", text: "Na primeira vez em que sofrer dano e sobreviver a cada turno, recebe +1 ATQ até o fim do turno." },
    ],
  },
  {
    id: "SET001-0003",
    setId: "SET001",
    collectorNumber: 3,
    name: "Zig, Cotovelo-Rápido",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "COMMON",
    cost: 1,
    attack: 1,
    defense: 2,
    rulesText: "CONEXÃO — Outro aliado recebe +1 ATQ até o fim do turno.",
    archetypes: ["Ataques em sequência"],
    effects: [{ trigger: "CONNECTION", text: "Outro aliado recebe +1 ATQ até o fim do turno." }],
  },
  {
    id: "SET001-0004",
    setId: "SET001",
    collectorNumber: 4,
    name: "Dente-13",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "UNCOMMON",
    cost: 1,
    attack: 3,
    defense: 1,
    rulesText: "Só pode atacar o Controller inimigo se outro aliado já atacou neste turno.",
    archetypes: ["Ataques em sequência"],
    effects: [{ trigger: "PASSIVE", text: "Só pode atacar o Controller inimigo se outro aliado já atacou neste turno." }],
  },
  {
    id: "SET001-0005",
    setId: "SET001",
    collectorNumber: 5,
    name: "Goma Nitro",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "COMMON",
    cost: 2,
    attack: 3,
    defense: 2,
    rulesText: "",
    archetypes: ["Pressão rápida"],
  },
  {
    id: "SET001-0006",
    setId: "SET001",
    collectorNumber: 6,
    name: "Biela Brava",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "COMMON",
    cost: 2,
    attack: 2,
    defense: 3,
    rulesText: "DESCONEXÃO — Cause 1 de dano ao Controller inimigo.",
    archetypes: ["Pressão rápida"],
    effects: [{ trigger: "DISCONNECTION", text: "Cause 1 de dano ao Controller inimigo." }],
  },
  {
    id: "SET001-0007",
    setId: "SET001",
    collectorNumber: 7,
    name: "Vika Voltagem",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "UNCOMMON",
    cost: 2,
    attack: 2,
    defense: 2,
    rulesText: "Pode atacar no turno em que entra se seu Controller sofreu dano neste turno.",
    archetypes: ["Dano próprio"],
    effects: [{ trigger: "PASSIVE", text: "Pode atacar no turno em que entra se seu Controller sofreu dano neste turno." }],
  },
  {
    id: "SET001-0008",
    setId: "SET001",
    collectorNumber: 8,
    name: "Toro-2",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "UNCOMMON",
    cost: 2,
    attack: 4,
    defense: 1,
    rulesText: "DESCONEXÃO — Cause 1 de dano ao seu Controller.",
    archetypes: ["Dano próprio"],
    effects: [{ trigger: "DISCONNECTION", text: "Cause 1 de dano ao seu Controller." }],
  },
  {
    id: "SET001-0009",
    setId: "SET001",
    collectorNumber: 9,
    name: "Anzol de Asfalto",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "RARE",
    cost: 2,
    attack: 2,
    defense: 2,
    rulesText: "CONEXÃO — Cause 1 de dano a um Controolz inimigo; ele não pode receber DEF neste turno.",
    archetypes: ["Pressão rápida"],
    effects: [{ trigger: "CONNECTION", text: "Cause 1 de dano a um Controolz inimigo; ele não pode receber DEF neste turno." }],
  },
  {
    id: "SET001-0010",
    setId: "SET001",
    collectorNumber: 10,
    name: "Grit",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "COMMON",
    cost: 3,
    attack: 4,
    defense: 3,
    rulesText: "",
    archetypes: ["Pressão rápida"],
  },
  {
    id: "SET001-0011",
    setId: "SET001",
    collectorNumber: 11,
    name: "Mara-13, Piloto de Rua",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "RARE",
    cost: 3,
    attack: 3,
    defense: 3,
    rulesText: "CONEXÃO — Se outro aliado já atacou neste turno, cause 1 de dano ao Controller inimigo.",
    archetypes: ["Ataques em sequência"],
    effects: [{ trigger: "CONNECTION", text: "Se outro aliado já atacou neste turno, cause 1 de dano ao Controller inimigo." }],
  },
  {
    id: "SET001-0012",
    setId: "SET001",
    collectorNumber: 12,
    name: "Rolo Compressor Júnior",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "COMMON",
    cost: 3,
    attack: 5,
    defense: 2,
    rulesText: "",
    archetypes: ["Pressão rápida"],
  },
  {
    id: "SET001-0013",
    setId: "SET001",
    collectorNumber: 13,
    name: "Escopeta de Ombro",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "UNCOMMON",
    cost: 3,
    attack: 3,
    defense: 4,
    rulesText: "Ao atacar, pode sofrer 1 de dano para receber +2 ATQ neste combate. Uma vez por turno.",
    archetypes: ["Dano próprio"],
    effects: [{ trigger: "PASSIVE", text: "Ao atacar, pode sofrer 1 de dano para receber +2 ATQ neste combate. Uma vez por turno." }],
  },
  {
    id: "SET001-0014",
    setId: "SET001",
    collectorNumber: 14,
    name: "Cromo, Dente Solto",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "UNCOMMON",
    cost: 3,
    attack: 2,
    defense: 4,
    rulesText: "Na primeira vez em que sofrer dano e sobreviver a cada turno, recebe +1 ATQ permanente.",
    archetypes: ["Dano próprio"],
    effects: [{ trigger: "PASSIVE", text: "Na primeira vez em que sofrer dano e sobreviver a cada turno, recebe +1 ATQ permanente." }],
  },
  {
    id: "SET001-0015",
    setId: "SET001",
    collectorNumber: 15,
    name: "Trinca-Sinal",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "COMMON",
    cost: 4,
    attack: 5,
    defense: 4,
    rulesText: "",
    archetypes: ["Pressão rápida"],
  },
  {
    id: "SET001-0016",
    setId: "SET001",
    collectorNumber: 16,
    name: "Nara Faísca",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "UNCOMMON",
    cost: 4,
    attack: 4,
    defense: 4,
    rulesText: "CONEXÃO — Cause 1 de dano a outro aliado. Ele recebe +3 ATQ até o fim do turno.",
    archetypes: ["Dano próprio"],
    effects: [{ trigger: "CONNECTION", text: "Cause 1 de dano a outro aliado. Ele recebe +3 ATQ até o fim do turno." }],
  },
  {
    id: "SET001-0017",
    setId: "SET001",
    collectorNumber: 17,
    name: "Cão 220V",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "RARE",
    cost: 4,
    attack: 6,
    defense: 3,
    rulesText: "Pode atacar no turno em que entra, mas nesse turno só pode atacar Controolz.",
    archetypes: ["Pressão rápida"],
    effects: [{ trigger: "PASSIVE", text: "Pode atacar no turno em que entra, mas nesse turno só pode atacar Controolz." }],
  },
  {
    id: "SET001-0018",
    setId: "SET001",
    collectorNumber: 18,
    name: "Brutus de Neon",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "UNCOMMON",
    cost: 5,
    attack: 6,
    defense: 5,
    rulesText: "Se outro aliado já atacou neste turno, recebe +2 ATQ durante seu combate.",
    archetypes: ["Ataques em sequência"],
    effects: [{ trigger: "PASSIVE", text: "Se outro aliado já atacou neste turno, recebe +2 ATQ durante seu combate." }],
  },
  {
    id: "SET001-0019",
    setId: "SET001",
    collectorNumber: 19,
    name: "Cida, Sem Freio",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "RARE",
    cost: 5,
    attack: 5,
    defense: 6,
    rulesText: "Custa 2 a menos se um aliado foi destruído neste turno, até o mínimo de 1.",
    archetypes: ["Ataques em sequência"],
    effects: [{ trigger: "PASSIVE", text: "Custa 2 a menos se um aliado foi destruído neste turno, até o mínimo de 1." }],
  },
  {
    id: "SET001-0020",
    setId: "SET001",
    collectorNumber: 20,
    name: "Motor-Carrasco",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "EPIC",
    cost: 6,
    attack: 6,
    defense: 6,
    rulesText: "CONEXÃO — Cause 2 de dano a todos os outros Controolz.",
    archetypes: ["Dano próprio"],
    effects: [{ trigger: "CONNECTION", text: "Cause 2 de dano a todos os outros Controolz." }],
  },
  {
    id: "SET001-0021",
    setId: "SET001",
    collectorNumber: 21,
    name: "Mara-13, Bandeira Rubra",
    type: "CONTROOLZ",
    cardClass: "RAGE",
    rarity: "LEGENDARY",
    cost: 7,
    attack: 7,
    defense: 7,
    rulesText: "CONEXÃO — Cause 2 de dano a um Controolz. Quando outro aliado sofrer dano de uma carta sua e sobreviver, cause 1 de dano ao Controller inimigo. No máximo duas vezes por turno.",
    archetypes: ["Dano próprio"],
    effects: [
      { trigger: "CONNECTION", text: "Cause 2 de dano a um Controolz." },
      { trigger: "PASSIVE", text: "Quando outro aliado sofrer dano de uma carta sua e sobreviver, cause 1 de dano ao Controller inimigo. No máximo duas vezes por turno." },
    ],
  },
  {
    id: "SET001-0022",
    setId: "SET001",
    collectorNumber: 22,
    name: "Curto-Circuito",
    type: "COMMAND",
    cardClass: "RAGE",
    rarity: "COMMON",
    cost: 1,
    rulesText: "Cause 1 de dano a um Controolz. Se for aliado e sobreviver, ele recebe +1 ATQ até o fim do turno.",
    archetypes: ["Dano próprio"],
    effects: [{ trigger: "COMMAND_RESOLVE", text: "Cause 1 de dano a um Controolz. Se for aliado e sobreviver, ele recebe +1 ATQ até o fim do turno." }],
  },
  {
    id: "SET001-0023",
    setId: "SET001",
    collectorNumber: 23,
    name: "Pisa Fundo",
    type: "COMMAND",
    cardClass: "RAGE",
    rarity: "COMMON",
    cost: 2,
    rulesText: "Um aliado recebe +2 ATQ neste turno. Se custar 2 ou menos, pode atacar no turno em que entrou.",
    archetypes: ["Pressão rápida"],
    effects: [{ trigger: "COMMAND_RESOLVE", text: "Um aliado recebe +2 ATQ neste turno. Se custar 2 ou menos, pode atacar no turno em que entrou." }],
  },
  {
    id: "SET001-0024",
    setId: "SET001",
    collectorNumber: 24,
    name: "Sem Capacete",
    type: "COMMAND",
    cardClass: "RAGE",
    rarity: "UNCOMMON",
    cost: 2,
    rulesText: "Um aliado recebe +3 ATQ e -1 DEF até o fim do turno.",
    archetypes: ["Dano próprio"],
    effects: [{ trigger: "COMMAND_RESOLVE", text: "Um aliado recebe +3 ATQ e -1 DEF até o fim do turno." }],
  },
  {
    id: "SET001-0025",
    setId: "SET001",
    collectorNumber: 25,
    name: "Linha Vermelha",
    type: "COMMAND",
    cardClass: "RAGE",
    rarity: "UNCOMMON",
    cost: 3,
    rulesText: "Cause 3 de dano a um Controolz inimigo. Se ele sobreviver, perde suas habilidades até o fim do turno.",
    archetypes: ["Pressão rápida"],
    effects: [{ trigger: "COMMAND_RESOLVE", text: "Cause 3 de dano a um Controolz inimigo. Se ele sobreviver, perde suas habilidades até o fim do turno." }],
  },
  {
    id: "SET001-0026",
    setId: "SET001",
    collectorNumber: 26,
    name: "Revanche Imediata",
    type: "COMMAND",
    cardClass: "RAGE",
    rarity: "RARE",
    cost: 3,
    rulesText: "Cause 2 de dano a um alvo inimigo; cause 4 em vez disso se um aliado foi destruído neste turno.",
    archetypes: ["Ataques em sequência"],
    effects: [{ trigger: "COMMAND_RESOLVE", text: "Cause 2 de dano a um alvo inimigo; cause 4 em vez disso se um aliado foi destruído neste turno." }],
  },
  {
    id: "SET001-0027",
    setId: "SET001",
    collectorNumber: 27,
    name: "Duas Marchas",
    type: "COMMAND",
    cardClass: "RAGE",
    rarity: "RARE",
    cost: 4,
    rulesText: "Um aliado pode atacar duas vezes neste turno. Após o primeiro ataque, ele sofre 2 de dano.",
    archetypes: ["Ataques em sequência"],
    effects: [{ trigger: "COMMAND_RESOLVE", text: "Um aliado pode atacar duas vezes neste turno. Após o primeiro ataque, ele sofre 2 de dano." }],
  },
  {
    id: "SET001-0028",
    setId: "SET001",
    collectorNumber: 28,
    name: "Tudo ou Nada",
    type: "COMMAND",
    cardClass: "RAGE",
    rarity: "EPIC",
    cost: 5,
    rulesText: "Seus aliados recebem +3 ATQ neste turno. No fim do turno, cada um que atacou sofre 2 de dano.",
    archetypes: ["Dano próprio"],
    effects: [{ trigger: "COMMAND_RESOLVE", text: "Seus aliados recebem +3 ATQ neste turno. No fim do turno, cada um que atacou sofre 2 de dano." }],
  },
  {
    id: "SET001-0029",
    setId: "SET001",
    collectorNumber: 29,
    name: "Colisão Programada",
    type: "COMMAND",
    cardClass: "RAGE",
    rarity: "EPIC",
    cost: 6,
    rulesText: "Escolha um aliado e um inimigo: cada um causa seu ATQ ao outro. Se o inimigo for destruído, cause 3 de dano ao Controller inimigo.",
    archetypes: ["Pressão rápida"],
    effects: [{ trigger: "COMMAND_RESOLVE", text: "Escolha um aliado e um inimigo: cada um causa seu ATQ ao outro. Se o inimigo for destruído, cause 3 de dano ao Controller inimigo." }],
  },
];
