'use client';
import { useState } from 'react';
import type { Locale, Tool } from '@/src/data/catalog';
import { copy } from '@/src/i18n';

type Dl={name:string;url:string};
const U:Record<Locale,Record<string,string>>={en:{choose:'Choose images',drag:'or drag and drop here',brightness:'Brightness',contrast:'Contrast',saturation:'Saturation',direction:'Direction',horizontal:'Horizontal',vertical:'Vertical',download:'Download'},pt:{choose:'Escolher imagens',drag:'ou arraste e solte aqui',brightness:'Brilho',contrast:'Contraste',saturation:'Saturação',direction:'Direção',horizontal:'Horizontal',vertical:'Vertical',download:'Baixar'},es:{choose:'Elegir imágenes',drag:'o arrastra y suelta aquí',brightness:'Brillo',contrast:'Contraste',saturation:'Saturación',direction:'Dirección',horizontal:'Horizontal',vertical:'Vertical',download:'Descargar'},zh:{choose:'选择图片',drag:'或拖放到这里',brightness:'亮度',contrast:'对比度',saturation:'饱和度',direction:'方向',horizontal:'水平',vertical:'垂直',download:'下载'},hi:{choose:'चित्र चुनें',drag:'या यहाँ खींचकर छोड़ें',brightness:'चमक',contrast:'कॉन्ट्रास्ट',saturation:'सैचुरेशन',direction:'दिशा',horizontal:'क्षैतिज',vertical:'ऊर्ध्वाधर',download:'डाउनलोड'}};
function load(file:File):Promise<HTMLImageElement>{const url=URL.createObjectURL(file);return new Promise((res,rej)=>{const img=new Image();img.onload=()=>{res(img);URL.revokeObjectURL(url)};img.onerror=()=>{URL.revokeObjectURL(url);rej(new Error('Unable to decode image'))};img.src=url})}
function blob(c:HTMLCanvasElement){return new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('Export failed')),'image/png'))}
export default function BulkSimpleImageRunner({tool,locale}:{tool:Tool;locale:Locale}){const t=copy[locale],u=U[locale],[files,setFiles]=useState<File[]>([]),[amount,setAmount]=useState('100'),[direction,setDirection]=useState('horizontal'),[downloads,setDownloads]=useState<Dl[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const mode=tool.slug==='bulk-change-brightness'?'brightness':tool.slug==='bulk-change-contrast'?'contrast':tool.slug==='bulk-change-saturation'?'saturation':'flip';function clear(){downloads.forEach(d=>URL.revokeObjectURL(d.url));setDownloads([]);setError('')}async function run(){setBusy(true);clear();try{const ds:Dl[]=[];for(let i=0;i<files.length;i++){const img=await load(files[i]),c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const x=c.getContext('2d')!;if(mode==='flip'){if(direction==='horizontal'){x.translate(c.width,0);x.scale(-1,1)}else{x.translate(0,c.height);x.scale(1,-1)}}else x.filter=`${mode}(${Math.max(0,Math.min(500,Number(amount)||100))}%)`;x.drawImage(img,0,0);const b=await blob(c);ds.push({name:`controols-${tool.slug}-${i+1}.png`,url:URL.createObjectURL(b)})}setDownloads(ds)}catch(e){setError(e instanceof Error?e.message:'Unable to process images')}finally{setBusy(false)}}return <section className="runner asset-runner"><div className="asset-controls"><label className="drop-zone"><input type="file" accept="image/*" multiple onChange={e=>{clear();setFiles(Array.from(e.target.files||[]))}}/><strong>{u.choose}</strong><span>{files.length?files.map(f=>f.name).join('\n'):u.drag}</span></label>{files.length>0&&<div className="smart-fields">{mode==='flip'?<label className="smart-field"><span>{u.direction}</span><select value={direction} onChange={e=>setDirection(e.target.value)}><option value="horizontal">{u.horizontal}</option><option value="vertical">{u.vertical}</option></select></label>:<label className="smart-field"><span>{u[mode]} (%)</span><input type="number" min="0" max="500" step="1" value={amount} onChange={e=>setAmount(e.target.value)}/></label>}</div>}{files.length>0&&<button className="primary" onClick={run} disabled={busy}>{busy?'…':t.run}</button>}</div>{error&&<div className="form-error">{error}</div>}{downloads.length>0&&<div className="asset-result"><div className="download-list">{downloads.map((d,i)=><a key={i} className="download-button" href={d.url} download={d.name}>{u.download} {i+1}</a>)}</div></div>}</section>}
