'use client';

import { useMemo, useState } from 'react';
import type { Locale, Tool } from '@/src/data/catalog';
import { copy } from '@/src/i18n';
import { runTool } from '@/src/lib/allExecutors';

type Field={key:string;kind?:'text'|'textarea';required?:boolean};
type Config={simple:Field[];advanced:Field[];example?:Record<string,string>};

export const guidedAiSlugs=new Set([
  'prompt-builder','system-prompt-builder','chatgpt-prompt-generator','social-media-prompt-generator','seo-prompt-generator','writing-prompt-generator',
  'image-prompt-generator','logo-prompt-generator','product-photo-prompt-generator','coding-prompt-generator','persona-prompt-generator'
]);

const ui:Record<Locale,Record<string,string>>={
 en:{intro:'Just describe what you need. Controols handles the prompt structure for you.',advanced:'Advanced options',advancedHelp:'Optional details for more control.',example:'Fill an example',create:'Create prompt',ready:'Prompt ready',goal:'What do you want the AI to do?',context:'Is there anything important the AI should know?',role:'Who should the AI act as? (optional)',constraints:'Anything it must follow or avoid? (optional)',output:'How should the answer be delivered? (optional)',rules:'What should this assistant always do?',tone:'What tone should it use? (optional)',topic:'What is the subject?',audience:'Who is this for? (optional)',format:'What format do you want? (optional)',subject:'What should appear in the image?',scene:'Where or how should it appear? (optional)',style:'What look or style do you want? (optional)',lighting:'Any lighting preference? (optional)',camera:'Any camera or lens preference? (optional)',negative:'What should be avoided? (optional)',brand:'What is the brand name?',industry:'What does the brand or business do?',values:'What should the brand communicate? (optional)',colors:'Preferred colors? (optional)',product:'What product should be photographed?',background:'What background do you want? (optional)',task:'What should the code do?',stack:'Any specific technology to use? (optional)',requirements:'What else must the solution include? (optional)',expertise:'What should this assistant be good at?',boundaries:'What should it never do? (optional)'},
 pt:{intro:'Descreva o que você precisa. O Controols organiza a estrutura do prompt por você.',advanced:'Opções avançadas',advancedHelp:'Detalhes opcionais para quem quer mais controle.',example:'Preencher um exemplo',create:'Criar prompt',ready:'Prompt pronto',goal:'O que você quer que a IA faça?',context:'Há algum contexto importante que a IA precisa saber?',role:'Quem a IA deve representar? (opcional)',constraints:'Existe alguma regra ou algo que deve ser evitado? (opcional)',output:'Como você quer receber a resposta? (opcional)',rules:'O que esse assistente deve sempre fazer?',tone:'Que tom ele deve usar? (opcional)',topic:'Qual é o assunto?',audience:'Para quem é o resultado? (opcional)',format:'Em que formato você quer o resultado? (opcional)',subject:'O que deve aparecer na imagem?',scene:'Onde ou como isso deve aparecer? (opcional)',style:'Que aparência ou estilo você quer? (opcional)',lighting:'Tem preferência de iluminação? (opcional)',camera:'Tem preferência de câmera ou lente? (opcional)',negative:'O que não deve aparecer? (opcional)',brand:'Qual é o nome da marca?',industry:'O que a marca ou negócio faz?',values:'O que a marca deve transmitir? (opcional)',colors:'Tem cores preferidas? (opcional)',product:'Qual produto deve aparecer na foto?',background:'Que tipo de fundo você quer? (opcional)',task:'O que o código precisa fazer?',stack:'Quer usar alguma tecnologia específica? (opcional)',requirements:'O que mais a solução precisa ter? (opcional)',expertise:'Em que esse assistente deve ser bom?',boundaries:'O que ele nunca deve fazer? (opcional)'},
 es:{intro:'Describe lo que necesitas. Controols organiza la estructura del prompt por ti.',advanced:'Opciones avanzadas',advancedHelp:'Detalles opcionales para tener más control.',example:'Rellenar un ejemplo',create:'Crear prompt',ready:'Prompt listo',goal:'¿Qué quieres que haga la IA?',context:'¿Hay algún contexto importante que deba conocer?',role:'¿Qué papel debe asumir la IA? (opcional)',constraints:'¿Hay alguna regla o algo que deba evitar? (opcional)',output:'¿Cómo quieres recibir la respuesta? (opcional)',rules:'¿Qué debe hacer siempre este asistente?',tone:'¿Qué tono debe usar? (opcional)',topic:'¿Cuál es el tema?',audience:'¿Para quién es el resultado? (opcional)',format:'¿En qué formato quieres el resultado? (opcional)',subject:'¿Qué debe aparecer en la imagen?',scene:'¿Dónde o cómo debe aparecer? (opcional)',style:'¿Qué aspecto o estilo quieres? (opcional)',lighting:'¿Alguna preferencia de iluminación? (opcional)',camera:'¿Alguna preferencia de cámara o lente? (opcional)',negative:'¿Qué debe evitarse? (opcional)',brand:'¿Cuál es el nombre de la marca?',industry:'¿A qué se dedica la marca o negocio?',values:'¿Qué debe transmitir la marca? (opcional)',colors:'¿Colores preferidos? (opcional)',product:'¿Qué producto debe aparecer en la foto?',background:'¿Qué fondo quieres? (opcional)',task:'¿Qué debe hacer el código?',stack:'¿Alguna tecnología específica? (opcional)',requirements:'¿Qué más debe incluir la solución? (opcional)',expertise:'¿En qué debe ser experto este asistente?',boundaries:'¿Qué nunca debe hacer? (opcional)'},
 zh:{intro:'只需描述你的需求，Controols 会帮你整理提示词结构。',advanced:'高级选项',advancedHelp:'可选细节，用于获得更多控制。',example:'填入示例',create:'生成提示词',ready:'提示词已生成',goal:'你希望 AI 做什么？',context:'AI 还需要了解哪些重要背景？',role:'AI 应扮演什么角色？（可选）',constraints:'有哪些必须遵守或避免的要求？（可选）',output:'希望以什么形式输出？（可选）',rules:'这个助手应始终遵守什么？',tone:'希望使用什么语气？（可选）',topic:'主题是什么？',audience:'内容面向谁？（可选）',format:'希望使用什么格式？（可选）',subject:'图片中应该出现什么？',scene:'希望它出现在哪里或以什么方式呈现？（可选）',style:'希望什么视觉风格？（可选）',lighting:'有灯光偏好吗？（可选）',camera:'有相机或镜头偏好吗？（可选）',negative:'不希望出现什么？（可选）',brand:'品牌名称是什么？',industry:'品牌或业务是做什么的？',values:'品牌应传达什么？（可选）',colors:'偏好的颜色？（可选）',product:'照片中要展示什么产品？',background:'希望什么背景？（可选）',task:'代码需要完成什么？',stack:'有指定技术吗？（可选）',requirements:'解决方案还必须包含什么？（可选）',expertise:'这个助手应擅长什么？',boundaries:'它绝不能做什么？（可选）'},
 hi:{intro:'बस बताइए आपको क्या चाहिए। Controols आपके लिए प्रॉम्प्ट की संरचना तैयार करता है।',advanced:'उन्नत विकल्प',advancedHelp:'अधिक नियंत्रण के लिए वैकल्पिक विवरण।',example:'उदाहरण भरें',create:'प्रॉम्प्ट बनाएँ',ready:'प्रॉम्प्ट तैयार',goal:'आप AI से क्या करवाना चाहते हैं?',context:'क्या कोई महत्वपूर्ण संदर्भ है जो AI को जानना चाहिए?',role:'AI को किस भूमिका में काम करना चाहिए? (वैकल्पिक)',constraints:'कोई नियम या ऐसी चीज़ जिसे टालना चाहिए? (वैकल्पिक)',output:'जवाब किस रूप में चाहिए? (वैकल्पिक)',rules:'इस सहायक को हमेशा क्या करना चाहिए?',tone:'किस टोन में जवाब दे? (वैकल्पिक)',topic:'विषय क्या है?',audience:'यह किसके लिए है? (वैकल्पिक)',format:'आउटपुट किस फ़ॉर्मेट में चाहिए? (वैकल्पिक)',subject:'इमेज में क्या दिखना चाहिए?',scene:'यह कहाँ या कैसे दिखना चाहिए? (वैकल्पिक)',style:'कौन-सा लुक या स्टाइल चाहिए? (वैकल्पिक)',lighting:'लाइटिंग की कोई पसंद? (वैकल्पिक)',camera:'कैमरा या लेंस की कोई पसंद? (वैकल्पिक)',negative:'क्या नहीं दिखना चाहिए? (वैकल्पिक)',brand:'ब्रांड का नाम क्या है?',industry:'ब्रांड या बिज़नेस क्या करता है?',values:'ब्रांड क्या संदेश दे? (वैकल्पिक)',colors:'पसंदीदा रंग? (वैकल्पिक)',product:'फोटो में कौन-सा प्रोडक्ट दिखना चाहिए?',background:'कैसा बैकग्राउंड चाहिए? (वैकल्पिक)',task:'कोड को क्या करना चाहिए?',stack:'कोई खास तकनीक इस्तेमाल करनी है? (वैकल्पिक)',requirements:'सॉल्यूशन में और क्या होना चाहिए? (वैकल्पिक)',expertise:'यह सहायक किस चीज़ में अच्छा होना चाहिए?',boundaries:'इसे कभी क्या नहीं करना चाहिए? (वैकल्पिक)'}
};

const placeholderPt:Record<string,string>={goal:'Ex.: escreva um e-mail profissional cobrando uma resposta de um cliente',context:'Ex.: o cliente recebeu a proposta há 5 dias e ainda não respondeu',role:'Ex.: especialista em atendimento ao cliente',constraints:'Ex.: não seja agressivo; não invente prazos',output:'Ex.: e-mail curto, com assunto e até 3 parágrafos',rules:'Ex.: explicar de forma simples; perguntar quando faltar uma informação essencial',topic:'Ex.: lançamento de uma loja de roupas femininas',audience:'Ex.: mulheres de 25 a 40 anos',format:'Ex.: legenda curta com chamada para ação',subject:'Ex.: um tênis branco premium sobre uma base de concreto',scene:'Ex.: estúdio minimalista com fundo cinza',style:'Ex.: fotografia publicitária realista e sofisticada',negative:'Ex.: texto deformado, baixa resolução, mãos extras',brand:'Ex.: Aurora Café',industry:'Ex.: cafeteria artesanal e torrefação de cafés especiais',product:'Ex.: perfume em frasco de vidro âmbar',task:'Ex.: criar uma página de login com validação de e-mail e senha',stack:'Ex.: Next.js e TypeScript',expertise:'Ex.: marketing digital para pequenos negócios'};
const placeholderEn:Record<string,string>={goal:'Example: write a professional follow-up email to a client',context:'Example: the proposal was sent 5 days ago and there was no reply',role:'Example: customer-success specialist',constraints:'Example: do not sound aggressive; do not invent deadlines',output:'Example: short email with subject and up to 3 paragraphs',rules:'Example: explain simply; ask when essential information is missing',topic:'Example: launch of a women’s clothing store',audience:'Example: women aged 25 to 40',format:'Example: short caption with a call to action',subject:'Example: a premium white sneaker on a concrete pedestal',scene:'Example: minimalist studio with a gray background',style:'Example: realistic premium advertising photography',negative:'Example: distorted text, low resolution, extra fingers',brand:'Example: Aurora Coffee',industry:'Example: specialty coffee shop and roastery',product:'Example: perfume in an amber glass bottle',task:'Example: build a login page with email and password validation',stack:'Example: Next.js and TypeScript',expertise:'Example: digital marketing for small businesses'};

function config(slug:string,locale:Locale):Config{
 const pt=locale==='pt',es=locale==='es';
 if(slug==='prompt-builder')return{simple:[{key:'goal',kind:'textarea',required:true},{key:'context',kind:'textarea'}],advanced:[{key:'role'},{key:'constraints',kind:'textarea'},{key:'output'}],example:pt?{goal:'Escreva um e-mail profissional para cobrar uma resposta de um cliente.',context:'Enviei uma proposta comercial há 5 dias e ainda não recebi retorno.',output:'E-mail curto, educado e pronto para enviar.'}:es?{goal:'Escribe un correo profesional para pedir una respuesta a un cliente.',context:'Envié una propuesta hace 5 días y aún no recibí respuesta.'}:{goal:'Write a professional follow-up email asking a client for a response.',context:'I sent a proposal 5 days ago and have not received a reply.'}};
 if(slug==='system-prompt-builder')return{simple:[{key:'role',required:true},{key:'rules',kind:'textarea',required:true}],advanced:[{key:'context',kind:'textarea'},{key:'tone'},{key:'output'}],example:pt?{role:'Assistente de atendimento ao cliente',rules:'Explique de forma simples. Seja educado. Quando faltar informação essencial, faça uma pergunta antes de responder.'}:es?{role:'Asistente de atención al cliente',rules:'Explica de forma simple. Sé amable. Si falta información esencial, pregunta antes de responder.'}:{role:'Customer support assistant',rules:'Explain things simply. Be polite. Ask a question when essential information is missing.'}};
 if(['chatgpt-prompt-generator','social-media-prompt-generator','seo-prompt-generator','writing-prompt-generator'].includes(slug))return{simple:[{key:'topic',required:true},{key:'goal',kind:'textarea',required:true}],advanced:[{key:'audience'},{key:'tone'},{key:'format'}],example:pt?{topic:'Lançamento de uma loja de roupas femininas',goal:'Criar uma publicação que apresente a loja e incentive as pessoas a visitar o perfil.',audience:'Mulheres de 25 a 40 anos'}:es?{topic:'Lanzamiento de una tienda de ropa femenina',goal:'Crear una publicación que presente la tienda y anime a visitar el perfil.'}:{topic:'Launch of a women’s clothing store',goal:'Create a post that introduces the store and encourages people to visit the profile.'}};
 if(slug==='image-prompt-generator')return{simple:[{key:'subject',kind:'textarea',required:true},{key:'scene'}],advanced:[{key:'style'},{key:'lighting'},{key:'camera'},{key:'negative',kind:'textarea'}],example:pt?{subject:'Um tênis branco premium sobre uma base de concreto',scene:'Estúdio minimalista com fundo cinza',style:'Fotografia publicitária realista e sofisticada'}:{subject:'A premium white sneaker on a concrete pedestal',scene:'Minimalist studio with a gray background',style:'Realistic premium advertising photography'}};
 if(slug==='logo-prompt-generator')return{simple:[{key:'brand',required:true},{key:'industry',required:true},{key:'style'}],advanced:[{key:'values',kind:'textarea'},{key:'colors'},{key:'negative',kind:'textarea'}],example:pt?{brand:'Aurora Café',industry:'Cafeteria artesanal e cafés especiais',style:'Minimalista, acolhedor e contemporâneo'}:{brand:'Aurora Coffee',industry:'Specialty coffee shop and roastery',style:'Minimal, warm and contemporary'}};
 if(slug==='product-photo-prompt-generator')return{simple:[{key:'product',kind:'textarea',required:true},{key:'scene'}],advanced:[{key:'lighting'},{key:'camera'},{key:'style'},{key:'background'}],example:pt?{product:'Perfume em frasco de vidro âmbar com tampa preta',scene:'Sobre uma pedra escura com reflexo suave',style:'Foto publicitária premium'}:{product:'Perfume in an amber glass bottle with a black cap',scene:'On a dark stone with a soft reflection',style:'Premium advertising photo'}};
 if(slug==='coding-prompt-generator')return{simple:[{key:'task',kind:'textarea',required:true},{key:'stack'}],advanced:[{key:'requirements',kind:'textarea'},{key:'constraints',kind:'textarea'},{key:'output'}],example:pt?{task:'Criar uma página de login com validação de e-mail e senha, mensagens de erro claras e botão de entrar.',stack:'Next.js e TypeScript'}:{task:'Build a login page with email and password validation, clear error messages, and a sign-in button.',stack:'Next.js and TypeScript'}};
 return{simple:[{key:'role',required:true},{key:'expertise',required:true}],advanced:[{key:'tone'},{key:'rules',kind:'textarea'},{key:'boundaries',kind:'textarea'}],example:pt?{role:'Consultor de marketing para pequenos negócios',expertise:'Posicionamento, redes sociais e aquisição de clientes'}:{role:'Marketing consultant for small businesses',expertise:'Positioning, social media and customer acquisition'}};
}

function hint(locale:Locale,key:string){if(locale==='pt')return placeholderPt[key]||'';if(locale==='en')return placeholderEn[key]||'';return ''}
function languageHint(locale:Locale){return locale==='pt'?'você quero objetivo não para com':locale==='es'?'¿quiero objetivo restricciones para con?':''}

export default function GuidedAiToolRunner({tool,locale}:{tool:Tool;locale:Locale}){
 const t=copy[locale],l=ui[locale],cfg=useMemo(()=>config(tool.slug,locale),[tool.slug,locale]);
 const all=[...cfg.simple,...cfg.advanced];
 const empty=()=>Object.fromEntries(all.map(f=>[f.key,'']));
 const [values,setValues]=useState<Record<string,string>>(empty);const [advanced,setAdvanced]=useState(false);const [output,setOutput]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const valid=cfg.simple.every(f=>!f.required||String(values[f.key]||'').trim());
 const update=(key:string,value:string)=>{setValues(v=>({...v,[key]:value}));setOutput('');setError('')};
 const clear=()=>{setValues(empty());setOutput('');setError('')};
 const applyExample=()=>{setValues(v=>({...v,...cfg.example}));setOutput('');setError('')};
 async function execute(){if(!valid)return;setBusy(true);setError('');try{setOutput(await runTool(tool.slug,String(tool.category),JSON.stringify({...values,__languageHint:languageHint(locale)})))}catch(e){setError(e instanceof Error?e.message:'Unable to process this value.')}finally{setBusy(false)}}
 return <section className="runner smart-form-runner guided-ai-runner">
   <div className="guided-ai-heading"><div><strong>{l.intro}</strong></div>{cfg.example&&<button type="button" className="guided-ai-example" onClick={applyExample}>✦ {l.example}</button>}</div>
   <div className="smart-fields guided-ai-fields">{cfg.simple.map(f=><GuidedField key={f.key} field={f} value={values[f.key]||''} locale={locale} onChange={v=>update(f.key,v)}/>)}</div>
   <button type="button" className="guided-ai-advanced-toggle" aria-expanded={advanced} onClick={()=>setAdvanced(v=>!v)}><span>{advanced?'−':'+'}</span><div><strong>{l.advanced}</strong><small>{l.advancedHelp}</small></div></button>
   {advanced&&<div className="smart-fields guided-ai-fields guided-ai-advanced">{cfg.advanced.map(f=><GuidedField key={f.key} field={f} value={values[f.key]||''} locale={locale} onChange={v=>update(f.key,v)}/>)}</div>}
   <div className="runner-actions"><button className="primary" onClick={execute} disabled={busy||!valid}>{busy?'…':l.create}</button><button onClick={clear}>{t.clear}</button></div>
   {error&&<div className="form-error" role="alert">{error}</div>}
   {output&&<div className="simple-output guided-ai-output"><strong>{l.ready}</strong><pre className="result-text">{output}</pre><button onClick={()=>navigator.clipboard.writeText(output)}>{t.copy}</button></div>}
 </section>
}

function GuidedField({field,value,locale,onChange}:{field:Field;value:string;locale:Locale;onChange:(value:string)=>void}){
 const l=ui[locale],id=`tool-${field.key}`;return <label className={`smart-field guided-ai-field${field.kind==='textarea'?' guided-ai-field-wide':''}`} htmlFor={id}><span>{l[field.key]||field.key}</span>{field.kind==='textarea'?<textarea id={id} value={value} required={field.required} placeholder={hint(locale,field.key)} onChange={e=>onChange(e.target.value)}/>:<input id={id} type="text" value={value} required={field.required} placeholder={hint(locale,field.key)} onChange={e=>onChange(e.target.value)}/>}</label>
}
