'use client';
import { useState } from 'react';
import type { Locale, Tool } from '@/src/data/catalog';
import { copy } from '@/src/i18n';

type QpdfModule={FS:{writeFile(path:string,data:Uint8Array):void;readFile(path:string):Uint8Array;unlink(path:string):void};callMain(args:string[]):number};declare global{interface Window{Module?: (options:Record<string,unknown>)=>Promise<QpdfModule>}}let modulePromise:Promise<QpdfModule>|null=null;
function qpdf(){if(modulePromise)return modulePromise;modulePromise=new Promise<QpdfModule>((resolve,reject)=>{const init=async()=>{try{if(!window.Module)throw new Error('QPDF unavailable');resolve(await window.Module({locateFile:()=>'/wasm/qpdf.wasm',noInitialRun:true,noExitRuntime:true}))}catch(e){reject(e)}};if(window.Module){void init();return}const s=document.createElement('script');s.src='/wasm/qpdf.js';s.onload=()=>void init();s.onerror=()=>reject(new Error('Unable to load PDF engine'));document.head.appendChild(s)});return modulePromise}
const U:Record<Locale,Record<string,string>>={en:{choose:'Choose PDF',drag:'or drag and drop here',password:'Password',confirm:'Confirm password',current:'Current password',download:'Download PDF',mismatch:'Passwords do not match.'},pt:{choose:'Escolher PDF',drag:'ou arraste e solte aqui',password:'Senha',confirm:'Confirmar senha',current:'Senha atual',download:'Baixar PDF',mismatch:'As senhas não coincidem.'},es:{choose:'Elegir PDF',drag:'o arrastra y suelta aquí',password:'Contraseña',confirm:'Confirmar contraseña',current:'Contraseña actual',download:'Descargar PDF',mismatch:'Las contraseñas no coinciden.'},zh:{choose:'选择 PDF',drag:'或拖放到这里',password:'密码',confirm:'确认密码',current:'当前密码',download:'下载 PDF',mismatch:'两次密码不一致。'},hi:{choose:'PDF चुनें',drag:'या यहाँ खींचकर छोड़ें',password:'पासवर्ड',confirm:'पासवर्ड की पुष्टि',current:'वर्तमान पासवर्ड',download:'PDF डाउनलोड करें',mismatch:'पासवर्ड मेल नहीं खाते।'}};
export default function PdfPasswordToolRunner({tool,locale}:{tool:Tool;locale:Locale}){const t=copy[locale],u=U[locale],protect=tool.slug==='protect-pdf',[file,setFile]=useState<File|null>(null),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[download,setDownload]=useState('');const valid=Boolean(file&&password&&(protect?password===confirm:true));async function run(){if(!file||!valid)return;setBusy(true);setError('');if(download)URL.revokeObjectURL(download);setDownload('');try{const mod=await qpdf(),id=`${Date.now()}-${Math.random().toString(36).slice(2)}`,input=`/in-${id}.pdf`,output=`/out-${id}.pdf`;mod.FS.writeFile(input,new Uint8Array(await file.arrayBuffer()));try{const args=protect?['--encrypt',password,password,'256','--',input,output]:[`--password=${password}`,'--decrypt',input,output],code=mod.callMain(args);if(code!==0)throw new Error('The PDF engine could not process this password.');const data=new Uint8Array(mod.FS.readFile(output)),blob=new Blob([data],{type:'application/pdf'});setDownload(URL.createObjectURL(blob))}finally{try{mod.FS.unlink(input)}catch{}try{mod.FS.unlink(output)}catch{}}}catch(e){setError(e instanceof Error?e.message:'Unable to process PDF')}finally{setBusy(false)}}return <section className="runner asset-runner"><div className="asset-controls"><label className="drop-zone"><input type="file" accept="application/pdf" onChange={e=>{setFile(e.target.files?.[0]||null);setError('');setDownload('')}}/><strong>{u.choose}</strong><span>{file?file.name:u.drag}</span></label>{file&&<div className="smart-fields"><label className="smart-field smart-field-wide"><span>{protect?u.password:u.current}</span><input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{protect&&<label className={`smart-field smart-field-wide${confirm&&confirm!==password?' invalid':''}`}><span>{u.confirm}</span><input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/>{confirm&&confirm!==password&&<small className="error-text">{u.mismatch}</small>}</label>}</div>}{file&&<button className="primary" onClick={run} disabled={busy||!valid}>{busy?'…':t.run}</button>}</div>{error&&<div className="form-error">{error}</div>}{download&&<div className="asset-result"><iframe className="pdf-preview" src={download} title="PDF preview"/><a className="download-button" href={download} download={`controols-${tool.slug}.pdf`}>{u.download}</a></div>}</section>}
