'use client';

import { useMemo, useState } from 'react';
import type { Locale, Tool } from '@/src/data/catalog';
import { copy } from '@/src/i18n';

type Dl={name:string;url:string};
type Loaded={img:HTMLImageElement;width:number;height:number};
const ui:Record<Locale,{choose:string;chooseMany:string;drag:string;options:string;run:string;download:string}>={
  en:{choose:'Choose image',chooseMany:'Choose images',drag:'or drag and drop here',options:'Options',run:'Apply',download:'Download'},
  pt:{choose:'Escolher imagem',chooseMany:'Escolher imagens',drag:'ou arraste e solte aqui',options:'Opções',run:'Aplicar',download:'Baixar'},
  es:{choose:'Elegir imagen',chooseMany:'Elegir imágenes',drag:'o arrastra y suelta aquí',options:'Opciones',run:'Aplicar',download:'Descargar'},
  zh:{choose:'选择图片',chooseMany:'选择多张图片',drag:'或拖放到这里',options:'选项',run:'应用',download:'下载'},
  hi:{choose:'चित्र चुनें',chooseMany:'चित्र चुनें',drag:'या यहाँ खींचकर छोड़ें',options:'विकल्प',run:'लागू करें',download:'डाउनलोड'}
};
function canvas(w:number,h:number){const c=document.createElement('canvas');c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));return c}
function blob(c:HTMLCanvasElement,type='image/png',q=.92){return new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('Export failed')),type,q))}
async function load(file:File):Promise<Loaded>{const url=URL.createObjectURL(file);return await new Promise((res,rej)=>{const img=new Image();img.onload=()=>{res({img,width:img.naturalWidth,height:img.naturalHeight});URL.revokeObjectURL(url)};img.onerror=()=>{URL.revokeObjectURL(url);rej(new Error('Unable to decode image'))};img.src=url})}
function draw(src:Loaded,w=src.width,h=src.height){const c=canvas(w,h);c.getContext('2d')!.drawImage(src.img,0,0,w,h);return c}
function n(s:string,i=0,d=0){const a=s.match(/-?\d+(?:\.\d+)?/g)?.map(Number)||[];return Number.isFinite(a[i])?a[i]:d}
function conv(c:HTMLCanvasElement,k:number[],div=1,bias=0){const x=c.getContext('2d')!,src=x.getImageData(0,0,c.width,c.height),out=x.createImageData(c.width,c.height),side=Math.sqrt(k.length)|0,half=side>>1;for(let y=0;y<c.height;y++)for(let xx=0;xx<c.width;xx++){const oi=(y*c.width+xx)*4;for(let ch=0;ch<3;ch++){let sum=0;for(let ky=0;ky<side;ky++)for(let kx=0;kx<side;kx++){const px=Math.max(0,Math.min(c.width-1,xx+kx-half)),py=Math.max(0,Math.min(c.height-1,y+ky-half));sum+=src.data[(py*c.width+px)*4+ch]*k[ky*side+kx]}out.data[oi+ch]=Math.max(0,Math.min(255,sum/div+bias))}out.data[oi+3]=src.data[oi+3]}x.putImageData(out,0,0)}
function mapPixels(c:HTMLCanvasElement,fn:(r:number,g:number,b:number,a:number)=>[number,number,number,number]){const x=c.getContext('2d')!,d=x.getImageData(0,0,c.width,c.height);for(let i=0;i<d.data.length;i+=4){const p=fn(d.data[i],d.data[i+1],d.data[i+2],d.data[i+3]);d.data[i]=p[0];d.data[i+1]=p[1];d.data[i+2]=p[2];d.data[i+3]=p[3]}x.putImageData(d,0,0)}
function normalize(slug:string){let s=slug.replace(/^bulk-/,'');const m:Record<string,string>={'change-brightness':'adjust-image-brightness','change-contrast':'adjust-image-contrast','change-saturation':'adjust-image-saturation','grayscale-image':'grayscale-image','invert-colors':'invert-image-colors','pixelate-effect':'pixelate-image','sepia-effect':'sepia-image','sharpen-image':'sharpen-image','blur-image':'blur-image','flip-image':'flip-image-horizontal','rotate-image':'rotate-image','resize-image':'resize-image','crop-image':'crop-image','get-colors-from-image':'get-colors-from-image','random-bitmap-generator':'random-bitmap-generator','split-image':'split-image'};return m[s]||s}
function palette(c:HTMLCanvasElement,count=8){const x=c.getContext('2d')!,d=x.getImageData(0,0,c.width,c.height).data,bins=new Map<string,number>(),step=Math.max(1,Math.floor(Math.sqrt(c.width*c.height/30000)));for(let y=0;y<c.height;y+=step)for(let xx=0;xx<c.width;xx+=step){const i=(y*c.width+xx)*4,r=Math.round(d[i]/32)*32,g=Math.round(d[i+1]/32)*32,b=Math.round(d[i+2]/32)*32,key=[Math.min(r,255),Math.min(g,255),Math.min(b,255)].map(v=>v.toString(16).padStart(2,'0')).join('').toUpperCase();bins.set(key,(bins.get(key)||0)+1)}return [...bins].sort((a,b)=>b[1]-a[1]).slice(0,count).map(([h])=>`#${h}`)}
function histogram(c:HTMLCanvasElement){const x=c.getContext('2d')!,d=x.getImageData(0,0,c.width,c.height).data,h=new Array(256).fill(0);for(let i=0;i<d.length;i+=4){const y=Math.round(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2]);h[y]++}return h}
function randomBitmap(w:number,h:number){const c=canvas(w,h),x=c.getContext('2d')!,d=x.createImageData(w,h);crypto.getRandomValues(d.data);for(let i=3;i<d.data.length;i+=4)d.data[i]=255;x.putImageData(d,0,0);return c}
function gradientImage(radial:boolean,w:number,h:number,option:string){const c=canvas(w,h),x=c.getContext('2d')!,colors=option.match(/#[0-9a-f]{6}/gi)||['#22c983','#111419'];const g=radial?x.createRadialGradient(w/2,h/2,0,w/2,h/2,Math.max(w,h)/2):x.createLinearGradient(0,0,w,h);colors.forEach((v,i)=>g.addColorStop(i/Math.max(1,colors.length-1),v));x.fillStyle=g;x.fillRect(0,0,w,h);return c}

export default function PineImageToolRunner({tool,locale}:{tool:Tool;locale:Locale}){
  const t=copy[locale],u=ui[locale],bulk=tool.slug.startsWith('bulk-'),base=normalize(tool.slug),generator=['random-bitmap-generator','image-gradient-generator','image-radial-gradient-generator'].includes(base),screenshot=base==='take-screenshot';
  const [files,setFiles]=useState<File[]>([]),[option,setOption]=useState(''),[downloads,setDownloads]=useState<Dl[]>([]),[preview,setPreview]=useState(''),[output,setOutput]=useState(''),[busy,setBusy]=useState(false);
  const multi=bulk||['merge-images','overlay-images'].includes(base);
  const needsOption=useMemo(()=>!['darken-image','lighten-image','grayscale-image','invert-image-colors','sepia-image','sharpen-image','edge-detection','edge-enhancement','emboss-effect','color-emboss-effect','remove-noise','equalize-image','rgb-channels'].includes(base),[base]);
  function clear(){downloads.forEach(d=>URL.revokeObjectURL(d.url));setDownloads([]);if(preview)URL.revokeObjectURL(preview);setPreview('');setOutput('')}
  async function capture(){setBusy(true);clear();try{const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false}),v=document.createElement('video');v.srcObject=stream;await v.play();await new Promise(r=>setTimeout(r,250));const c=canvas(v.videoWidth,v.videoHeight);c.getContext('2d')!.drawImage(v,0,0);stream.getTracks().forEach(x=>x.stop());const b=await blob(c),d={name:'controols-screenshot.png',url:URL.createObjectURL(b)};setDownloads([d]);setPreview(d.url);setOutput(`${c.width} × ${c.height}px`)}catch(e){setOutput(e instanceof Error?e.message:'Unable to capture screen')}setBusy(false)}
  async function one(file:File,index:number):Promise<Dl[]>{const src=await load(file),c0=draw(src);let c=c0;const amount=n(option,0,20),arr=n(option,0,0),arr2=n(option,1,0);
    if(base==='darken-image'||base==='lighten-image'||base==='adjust-image-brightness'||base==='adjust-image-contrast'||base==='adjust-image-saturation'||base==='change-vibrance'||base==='change-exposure'||base==='adjust-hue'||base==='adjust-gamma'||base==='grayscale-image'||base==='sepia-image'||base==='invert-image-colors'||base==='blur-image'){
      c=canvas(src.width,src.height);const x=c.getContext('2d')!;let f='none';if(base==='darken-image')f=`brightness(${Math.max(0,100-(amount||20))}%)`;if(base==='lighten-image')f=`brightness(${100+(amount||20)}%)`;if(base==='adjust-image-brightness')f=`brightness(${amount||120}%)`;if(base==='adjust-image-contrast')f=`contrast(${amount||120}%)`;if(base==='adjust-image-saturation')f=`saturate(${amount||120}%)`;if(base==='change-vibrance')f=`saturate(${100+(amount||25)}%) contrast(105%)`;if(base==='change-exposure')f=`brightness(${100+(amount||20)}%)`;if(base==='adjust-hue')f=`hue-rotate(${amount||30}deg)`;if(base==='adjust-gamma'){const g=Math.max(.1,amount||1.2);mapPixels(c0,(r,gc,b,a)=>[255*Math.pow(r/255,1/g),255*Math.pow(gc/255,1/g),255*Math.pow(b/255,1/g),a]);c=c0;f='none'}if(base==='grayscale-image')f='grayscale(1)';if(base==='sepia-image')f='sepia(1)';if(base==='invert-image-colors')f='invert(1)';if(base==='blur-image')f=`blur(${Math.max(1,amount||6)}px)`;if(f!=='none'){x.filter=f;x.drawImage(src.img,0,0)}}
    else if(base==='sharpen-image'){conv(c,[0,-1,0,-1,5,-1,0,-1,0])}
    else if(base==='emboss-effect'){conv(c,[-2,-1,0,-1,1,1,0,1,2],1,128)}
    else if(base==='color-emboss-effect'){conv(c,[-2,-1,0,-1,1,1,0,1,2],1,96)}
    else if(base==='edge-detection'){conv(c,[-1,-1,-1,-1,8,-1,-1,-1,-1])}
    else if(base==='edge-enhancement'){conv(c,[0,-1,0,-1,9,-1,0,-1,0])}
    else if(base==='threshold-black-white'){const th=amount||128;mapPixels(c,(r,g,b,a)=>{const y=.2126*r+.7152*g+.0722*b,v=y>=th?255:0;return[v,v,v,a]})}
    else if(base==='posterize-effect'){const levels=Math.max(2,Math.min(16,amount||5)),step=255/(levels-1);mapPixels(c,(r,g,b,a)=>[Math.round(r/step)*step,Math.round(g/step)*step,Math.round(b/step)*step,a])}
    else if(base==='solarize-effect'){const th=amount||128;mapPixels(c,(r,g,b,a)=>[r>th?255-r:r,g>th?255-g:g,b>th?255-b:b,a])}
    else if(base==='add-noise'){const amp=Math.max(1,amount||25);mapPixels(c,(r,g,b,a)=>{const z=(Math.random()-.5)*2*amp;return[r+z,g+z,b+z,a]})}
    else if(base==='remove-noise'){const x=c.getContext('2d')!,srcd=x.getImageData(0,0,c.width,c.height),out=x.createImageData(c.width,c.height);for(let y=0;y<c.height;y++)for(let xx=0;xx<c.width;xx++){for(let ch=0;ch<3;ch++){let s=0,k=0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const px=Math.max(0,Math.min(c.width-1,xx+dx)),py=Math.max(0,Math.min(c.height-1,y+dy));s+=srcd.data[(py*c.width+px)*4+ch];k++}out.data[(y*c.width+xx)*4+ch]=s/k}out.data[(y*c.width+xx)*4+3]=srcd.data[(y*c.width+xx)*4+3]}x.putImageData(out,0,0)}
    else if(base==='pixelate-image'||base==='censor-photo'){const s=Math.max(2,amount||14),sm=canvas(Math.ceil(src.width/s),Math.ceil(src.height/s));sm.getContext('2d')!.drawImage(src.img,0,0,sm.width,sm.height);c=canvas(src.width,src.height);const x=c.getContext('2d')!;x.imageSmoothingEnabled=false;x.drawImage(sm,0,0,c.width,c.height)}
    else if(base==='vignette-effect'){const x=c.getContext('2d')!,g=x.createRadialGradient(c.width/2,c.height/2,Math.min(c.width,c.height)*.2,c.width/2,c.height/2,Math.max(c.width,c.height)*.7);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,`rgba(0,0,0,${Math.min(.95,(amount||55)/100)})`);x.fillStyle=g;x.fillRect(0,0,c.width,c.height)}
    else if(base==='colorize-image'||base==='duotone-effect'){const color=option.match(/#[0-9a-f]{6}/i)?.[0]||'#22c983',rgb=[parseInt(color.slice(1,3),16),parseInt(color.slice(3,5),16),parseInt(color.slice(5,7),16)];mapPixels(c,(r,g,b,a)=>{const y=(r+g+b)/3/255;return base==='duotone-effect'?[rgb[0]*y,40+(rgb[1]*y),80+(rgb[2]*y),a]:[(r+rgb[0])/2,(g+rgb[1])/2,(b+rgb[2])/2,a]})}
    else if(base==='adjust-channels'){const rr=arr||100,gg=arr2||100,bb=n(option,2,100);mapPixels(c,(r,g,b,a)=>[r*rr/100,g*gg/100,b*bb/100,a])}
    else if(base==='adjust-hsl'){const h=arr||0,s=arr2||100,l=n(option,2,100);c=canvas(src.width,src.height);const x=c.getContext('2d')!;x.filter=`hue-rotate(${h}deg) saturate(${s}%) brightness(${l}%)`;x.drawImage(src.img,0,0)}
    else if(base==='brightness-contrast'){const br=arr||110,co=arr2||110;c=canvas(src.width,src.height);const x=c.getContext('2d')!;x.filter=`brightness(${br}%) contrast(${co}%)`;x.drawImage(src.img,0,0)}
    else if(base==='glow-effect'){const x=c.getContext('2d')!;x.save();x.globalCompositeOperation='screen';x.filter=`blur(${Math.max(2,amount||8)}px)`;x.globalAlpha=.6;x.drawImage(src.img,0,0);x.restore()}
    else if(base==='tilt-shift-effect'){const x=c.getContext('2d')!,tmp=canvas(c.width,c.height),tx=tmp.getContext('2d')!;tx.filter=`blur(${Math.max(4,amount||10)}px)`;tx.drawImage(src.img,0,0);x.clearRect(0,0,c.width,c.height);x.drawImage(tmp,0,0);x.save();x.beginPath();x.rect(0,c.height*.35,c.width,c.height*.3);x.clip();x.filter='none';x.drawImage(src.img,0,0);x.restore()}
    else if(base==='round-corners-image'){const r=Math.max(1,amount||32),out=canvas(c.width,c.height),x=out.getContext('2d')!;x.beginPath();x.roundRect(0,0,c.width,c.height,r);x.clip();x.drawImage(src.img,0,0);c=out}
    else if(base==='rotate-image'){const deg=amount||90,rad=deg*Math.PI/180,sw=Math.abs(Math.cos(rad)*src.width)+Math.abs(Math.sin(rad)*src.height),sh=Math.abs(Math.sin(rad)*src.width)+Math.abs(Math.cos(rad)*src.height);c=canvas(sw,sh);const x=c.getContext('2d')!;x.translate(c.width/2,c.height/2);x.rotate(rad);x.drawImage(src.img,-src.width/2,-src.height/2)}
    else if(base==='flip-image-horizontal'){c=canvas(src.width,src.height);const x=c.getContext('2d')!;x.translate(src.width,0);x.scale(-1,1);x.drawImage(src.img,0,0)}
    else if(base==='resize-image'){const w=Math.max(1,arr||Math.round(src.width*.5)),h=Math.max(1,arr2||Math.round(src.height*w/src.width));c=draw(src,w,h)}
    else if(base==='crop-image'){const x0=arr||0,y0=arr2||0,w=Math.max(1,n(option,2,src.width-x0)),h=Math.max(1,n(option,3,src.height-y0));c=canvas(w,h);c.getContext('2d')!.drawImage(src.img,x0,y0,w,h,0,0,w,h)}
    else if(base==='blurred-frame-image-generator'){const w=Math.max(src.width,arr||1920),h=Math.max(src.height,arr2||1080),out=canvas(w,h),x=out.getContext('2d')!;x.filter='blur(28px) brightness(65%)';x.drawImage(src.img,-40,-40,w+80,h+80);x.filter='none';const s=Math.min(w/src.width,h/src.height),iw=src.width*s,ih=src.height*s;x.drawImage(src.img,(w-iw)/2,(h-ih)/2,iw,ih);c=out}
    else if(base==='remove-background'){const x=c.getContext('2d')!,d=x.getImageData(0,0,c.width,c.height),r0=d.data[0],g0=d.data[1],b0=d.data[2],tol=Math.max(5,amount||35);for(let i=0;i<d.data.length;i+=4){const dist=Math.hypot(d.data[i]-r0,d.data[i+1]-g0,d.data[i+2]-b0);if(dist<tol)d.data[i+3]=0}x.putImageData(d,0,0)}
    else if(base==='special-filters'){c=canvas(src.width,src.height);const x=c.getContext('2d')!,name=option.toLowerCase(),f=name.includes('vintage')?'sepia(.45) contrast(1.15) saturate(.85)':name.includes('lomo')?'contrast(1.3) saturate(1.35)':name.includes('clarity')?'contrast(1.2) saturate(1.1)':name.includes('sunrise')?'sepia(.2) saturate(1.3) brightness(1.08)':'contrast(1.12) saturate(1.08)';x.filter=f;x.drawImage(src.img,0,0)}
    else if(base==='equalize-image'||base==='equalize-image-area'){const x=c.getContext('2d')!,d=x.getImageData(0,0,c.width,c.height),hist=histogram(c),cdf:number[]=[],total=c.width*c.height;let sum=0;for(let i=0;i<256;i++){sum+=hist[i];cdf[i]=sum/total*255}for(let i=0;i<d.data.length;i+=4){const y=Math.round(.2126*d.data[i]+.7152*d.data[i+1]+.0722*d.data[i+2]),scale=y?cdf[y]/y:1;d.data[i]*=scale;d.data[i+1]*=scale;d.data[i+2]*=scale}x.putImageData(d,0,0)}
    else if(base==='clip-image'){const low=Math.max(0,arr||30),high=Math.min(255,arr2||225);mapPixels(c,(r,g,b,a)=>[r<low?0:r>high?255:r,g<low?0:g>high?255:g,b<low?0:b>high?255:b,a])}
    else if(base==='svg-converter-viewer'){c=draw(src)}
    if(base==='get-colors-from-image'){setOutput(palette(c,Math.max(2,amount||8)).join('\n'));return[]}
    if(base==='image-histogram'){const h=histogram(c),max=Math.max(...h);setOutput(h.map((v,i)=>`${i}\t${v}\t${'█'.repeat(Math.round(v/max*30))}`).join('\n'));return[]}
    if(base==='rgb-channels'){const x=c.getContext('2d')!,d=x.getImageData(0,0,c.width,c.height),outs:Dl[]=[];for(let ch=0;ch<3;ch++){const cc=canvas(c.width,c.height),cx=cc.getContext('2d')!,dd=cx.createImageData(c.width,c.height);for(let i=0;i<d.data.length;i+=4){dd.data[i+ch]=d.data[i+ch];dd.data[i+3]=d.data[i+3]}cx.putImageData(dd,0,0);const bb=await blob(cc),name=`controols-${['red','green','blue'][ch]}-${index+1}.png`;outs.push({name,url:URL.createObjectURL(bb)})}return outs}
    if(base==='split-image'){const cols=Math.max(1,arr||2),rows=Math.max(1,arr2||2),outs:Dl[]=[];for(let yy=0;yy<rows;yy++)for(let xx=0;xx<cols;xx++){const w=Math.floor(c.width/cols),h=Math.floor(c.height/rows),cc=canvas(w,h);cc.getContext('2d')!.drawImage(c,xx*w,yy*h,w,h,0,0,w,h);const bb=await blob(cc),name=`controols-split-${index+1}-${yy+1}-${xx+1}.png`;outs.push({name,url:URL.createObjectURL(bb)})}return outs}
    const bb=await blob(c),name=`controols-${base}-${index+1}.png`;return[{name,url:URL.createObjectURL(bb)}]
  }
  async function process(){setBusy(true);clear();try{
    if(generator){const w=Math.max(16,n(option,0,1200)),h=Math.max(16,n(option,1,800)),count=bulk?Math.max(1,Math.min(30,n(option,2,5))):1,ds:Dl[]=[];for(let i=0;i<count;i++){const c=base==='random-bitmap-generator'?randomBitmap(w,h):gradientImage(base==='image-radial-gradient-generator',w,h,option);const b=await blob(c),d={name:`controols-${base}-${i+1}.png`,url:URL.createObjectURL(b)};ds.push(d)}setDownloads(ds);setPreview(ds[0]?.url||'');setOutput(`${ds.length} image(s) generated`);return}
    if(!files.length)throw new Error('Choose an image first.');
    if(['merge-images','overlay-images'].includes(base)){if(files.length<2)throw new Error('Choose at least two images.');const loaded=await Promise.all(files.map(load)),w=Math.max(...loaded.map(x=>x.width)),h=Math.max(...loaded.map(x=>x.height)),c=canvas(w,h),x=c.getContext('2d')!;if(base==='merge-images'){let xpos=0;const total=loaded.reduce((s,z)=>s+z.width,0),out=canvas(total,Math.max(...loaded.map(z=>z.height))),ox=out.getContext('2d')!;for(const z of loaded){ox.drawImage(z.img,xpos,0);xpos+=z.width}const b=await blob(out),d={name:'controols-merge-images.png',url:URL.createObjectURL(b)};setDownloads([d]);setPreview(d.url)}else{loaded.forEach((z,i)=>{x.globalAlpha=i?Math.max(.05,Math.min(1,n(option,0,.65))):1;x.drawImage(z.img,0,0,w,h)});const b=await blob(c),d={name:'controols-overlay-images.png',url:URL.createObjectURL(b)};setDownloads([d]);setPreview(d.url)}return}
    const ds:Dl[]=[];for(let i=0;i<files.length;i++)ds.push(...await one(files[i],i));setDownloads(ds);if(ds[0])setPreview(ds[0].url);if(!output)setOutput(`${files.length} image(s) processed · ${ds.length} file(s) ready`)
  }catch(e){setOutput(`Error: ${e instanceof Error?e.message:'Unable to process image'}`)}finally{setBusy(false)}}
  const hasInput=files.length>0||generator;
  if(screenshot)return <section className="runner asset-runner"><div className="asset-controls"><button className="primary big-action" onClick={capture} disabled={busy}>{busy?'…':t.run}</button></div>{(preview||output)&&<div className="asset-result result-after">{preview&&<img src={preview} alt="Screenshot"/>}{output&&<div className="result-summary">{output}</div>}{downloads.map(d=><a className="download-button" key={d.url} href={d.url} download={d.name}>↓ {u.download}</a>)}</div>}</section>;
  return <section className="runner asset-runner"><div className="asset-controls">{!generator&&<label className="drop-zone compact-upload"><input type="file" accept="image/*,.svg" multiple={multi} onChange={e=>{clear();setFiles(Array.from(e.target.files||[]))}}/><strong>{multi?u.chooseMany:u.choose}</strong><span>{files.length?files.map(f=>f.name).join('\n'):u.drag}</span></label>}{(hasInput&&needsOption||generator)&&<div className="tool-options"><div className="tool-options-title">{u.options}</div><label className="option-field"><input value={option} onChange={e=>setOption(e.target.value)} placeholder={generator?'1200 800 #22c983 #111419':base==='remove-background'?'35 (tolerance)':base==='resize-image'?'1200 800':base==='crop-image'?'x y width height':base==='split-image'?'2 2':'value / color / preset'}/></label></div>}{hasInput&&<button className="primary big-action" onClick={process} disabled={busy}>{busy?'…':u.run}</button>}</div>{(preview||output||downloads.length>0)&&<div className="asset-result result-after">{preview&&<img src={preview} alt="Result preview"/>}{output&&<pre className="result-text">{output}</pre>}{downloads.length>0&&<div className="download-list">{downloads.map((d,i)=><a className="download-button" href={d.url} download={d.name} key={`${d.url}-${i}`}>↓ {d.name}</a>)}</div>}</div>}</section>
}
