'use client';

import { useState } from 'react';
import type { Locale, Tool } from '@/src/data/catalog';
import { copy } from '@/src/i18n';

type Dl={name:string;url:string};
const ui:Record<Locale,Record<string,string>>={
  en:{choose:'Choose file',chooseMany:'Choose files',drag:'or drag and drop here',download:'Download',chunk:'Part size',size:'File size',unit:'Unit',extension:'Extension',filename:'Output file name',damage:'Bytes to modify (%)',base64:'Base64 data'},
  pt:{choose:'Escolher arquivo',chooseMany:'Escolher arquivos',drag:'ou arraste e solte aqui',download:'Baixar',chunk:'Tamanho de cada parte',size:'Tamanho do arquivo',unit:'Unidade',extension:'Extensão',filename:'Nome do arquivo de saída',damage:'Percentual de bytes a alterar',base64:'Dados em Base64'},
  es:{choose:'Elegir archivo',chooseMany:'Elegir archivos',drag:'o arrastra y suelta aquí',download:'Descargar',chunk:'Tamaño de cada parte',size:'Tamaño del archivo',unit:'Unidad',extension:'Extensión',filename:'Nombre del archivo de salida',damage:'Porcentaje de bytes a modificar',base64:'Datos Base64'},
  zh:{choose:'选择文件',chooseMany:'选择多个文件',drag:'或拖放到这里',download:'下载',chunk:'分块大小',size:'文件大小',unit:'单位',extension:'扩展名',filename:'输出文件名',damage:'修改字节百分比',base64:'Base64 数据'},
  hi:{choose:'फ़ाइल चुनें',chooseMany:'फ़ाइलें चुनें',drag:'या यहाँ खींचकर छोड़ें',download:'डाउनलोड',chunk:'भाग का आकार',size:'फ़ाइल आकार',unit:'इकाई',extension:'एक्सटेंशन',filename:'आउटपुट फ़ाइल नाम',damage:'बदलने वाले बाइट (%)',base64:'Base64 डेटा'}
};
function bytesFor(value:number,unit:string){const mul=unit==='GB'?1073741824:unit==='MB'?1048576:unit==='KB'?1024:1;return Math.max(1,Math.floor(value*mul))}
function randomBytes(size:number){const out=new Uint8Array(size);for(let offset=0;offset<size;offset+=65536)crypto.getRandomValues(out.subarray(offset,Math.min(size,offset+65536)));return out}
export default function PineFileToolRunner({tool,locale}:{tool:Tool;locale:Locale}){
  const t=copy[locale],u=ui[locale],[files,setFiles]=useState<File[]>([]),[text,setText]=useState(''),[value,setValue]=useState('1'),[unit,setUnit]=useState('MB'),[extension,setExtension]=useState('bin'),[filename,setFilename]=useState('controols-joined-file.bin'),[damage,setDamage]=useState('1'),[downloads,setDownloads]=useState<Dl[]>([]),[output,setOutput]=useState(''),[busy,setBusy]=useState(false);
  const multiple=tool.slug==='join-files',textInput=tool.slug==='base64-decode-file',generator=['random-file-generator','corrupt-file-generator'].includes(tool.slug),ready=textInput?Boolean(text.trim()):generator||files.length>0;
  function clear(){downloads.forEach(d=>URL.revokeObjectURL(d.url));setDownloads([]);setOutput('')}
  async function process(){setBusy(true);clear();try{
    if(generator){const size=Math.min(bytesFor(Number(value)||1,unit),128*1048576),data=randomBytes(size),d={name:`controols-${tool.slug}.${extension.replace(/^\./,'')||'bin'}`,url:URL.createObjectURL(new Blob([data]))};setDownloads([d]);setOutput(`${(size/1048576).toFixed(2)} MB`);return}
    if(tool.slug==='base64-decode-file'){const raw=text.includes(',')?text.split(',').pop()!:text,bin=atob(raw.replace(/\s+/g,'')),data=Uint8Array.from(bin,c=>c.charCodeAt(0)),d={name:'controols-decoded-file.bin',url:URL.createObjectURL(new Blob([data]))};setDownloads([d]);setOutput(`${data.length} bytes`);return}
    if(!files.length)throw new Error('Choose a file first.');
    if(tool.slug==='base64-encode-file'){const result=await new Promise<string>((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',').pop()||'');r.onerror=()=>rej(r.error);r.readAsDataURL(files[0])});setOutput(result);return}
    if(tool.slug==='split-files'){const file=files[0],chunk=Math.min(bytesFor(Number(value)||1,unit),Math.max(1,file.size)),buf=new Uint8Array(await file.arrayBuffer()),ds:Dl[]=[];for(let start=0,i=1;start<buf.length;start+=chunk,i++){const part=buf.slice(start,Math.min(buf.length,start+chunk)),name=`${file.name}.part${String(i).padStart(3,'0')}`;ds.push({name,url:URL.createObjectURL(new Blob([part]))})}setDownloads(ds);setOutput(`${ds.length} parts · ${(chunk/1048576).toFixed(2)} MB max each`);return}
    if(tool.slug==='join-files'){const buffers=await Promise.all(files.map(f=>f.arrayBuffer())),d={name:filename.trim()||'controols-joined-file.bin',url:URL.createObjectURL(new Blob(buffers))};setDownloads([d]);setOutput(`${files.length} parts joined`);return}
    if(tool.slug==='corrupt-file'){const file=files[0],data=new Uint8Array(await file.arrayBuffer()),pct=Math.max(.001,Math.min(.25,(Number(damage)||1)/100)),changes=Math.max(1,Math.floor(data.length*pct));for(let i=0;i<changes;i++){const p=Math.floor(Math.random()*data.length);data[p]=Math.floor(Math.random()*256)}const d={name:`corrupted-${file.name}`,url:URL.createObjectURL(new Blob([data],{type:file.type}))};setDownloads([d]);setOutput(`${changes} bytes modified (${(pct*100).toFixed(2)}%)`)}
  }catch(e){setOutput(`Error: ${e instanceof Error?e.message:'Unable to process file'}`)}finally{setBusy(false)}}
  return <section className="runner asset-runner"><div className="asset-controls">{textInput?<label className="smart-field"><span>{u.base64}</span><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Base64…"/></label>:!generator&&<label className="drop-zone compact-upload"><input type="file" multiple={multiple} onChange={e=>{clear();setFiles(Array.from(e.target.files||[]))}}/><strong>{multiple?u.chooseMany:u.choose}</strong><span>{files.length?files.map(f=>f.name).join('\n'):u.drag}</span></label>}{ready&&['split-files','random-file-generator','corrupt-file-generator'].includes(tool.slug)&&<div className="smart-fields"><label className="smart-field"><span>{tool.slug==='split-files'?u.chunk:u.size}</span><input type="number" min="0.001" step="0.001" value={value} onChange={e=>setValue(e.target.value)}/></label><label className="smart-field"><span>{u.unit}</span><select value={unit} onChange={e=>setUnit(e.target.value)}><option>B</option><option>KB</option><option>MB</option><option>GB</option></select></label>{generator&&<label className="smart-field smart-field-wide"><span>{u.extension}</span><input value={extension} onChange={e=>setExtension(e.target.value.replace(/[^a-z0-9]/gi,''))} placeholder="bin"/></label>}</div>}{ready&&tool.slug==='join-files'&&<label className="smart-field"><span>{u.filename}</span><input value={filename} onChange={e=>setFilename(e.target.value)}/></label>}{ready&&tool.slug==='corrupt-file'&&<label className="smart-field"><span>{u.damage}</span><input type="number" min="0.1" max="25" step="0.1" value={damage} onChange={e=>setDamage(e.target.value)}/></label>}{ready&&<button className="primary big-action" onClick={process} disabled={busy}>{busy?'…':t.run}</button>}</div>{(output||downloads.length>0)&&<div className="asset-result result-after">{output&&<pre className="result-text">{output}</pre>}{downloads.length>0&&<div className="download-list">{downloads.map((d,i)=><a className="download-button" href={d.url} download={d.name} key={i}>↓ {d.name}</a>)}</div>}</div>}</section>
}
