'use client';

import { useEffect, useRef, useState } from 'react';
import type { Locale, Tool } from '@/src/data/catalog';

type TimeCopy={start:string;pause:string;reset:string;stop:string;record:string;days:string;hours:string;minutes:string;seconds:string;download:string};
const ui:Record<Locale,TimeCopy>={
  en:{start:'Start',pause:'Pause',reset:'Reset',stop:'Stop',record:'Start recording',days:'Days',hours:'Hours',minutes:'Minutes',seconds:'Seconds',download:'Download recording'},
  pt:{start:'Iniciar',pause:'Pausar',reset:'Zerar',stop:'Parar',record:'Iniciar gravação',days:'Dias',hours:'Horas',minutes:'Minutos',seconds:'Segundos',download:'Baixar gravação'},
  es:{start:'Iniciar',pause:'Pausar',reset:'Reiniciar',stop:'Detener',record:'Iniciar grabación',days:'Días',hours:'Horas',minutes:'Minutos',seconds:'Segundos',download:'Descargar grabación'},
  zh:{start:'开始',pause:'暂停',reset:'重置',stop:'停止',record:'开始录制',days:'天',hours:'小时',minutes:'分钟',seconds:'秒',download:'下载录制'},
  hi:{start:'शुरू करें',pause:'रोकें',reset:'रीसेट',stop:'बंद करें',record:'रिकॉर्डिंग शुरू करें',days:'दिन',hours:'घंटे',minutes:'मिनट',seconds:'सेकंड',download:'रिकॉर्डिंग डाउनलोड करें'}
};
function fmt(ms:number){const total=Math.max(0,Math.floor(ms/1000)),d=Math.floor(total/86400),h=Math.floor(total%86400/3600),m=Math.floor(total%3600/60),s=total%60;return `${d?`${d}d `:''}${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}

function Timer({locale}:{locale:Locale}){const u=ui[locale],[parts,setParts]=useState([0,0,5,0]),[remaining,setRemaining]=useState(300000),[running,setRunning]=useState(false),end=useRef(0);const total=()=>((parts[0]*86400)+(parts[1]*3600)+(parts[2]*60)+parts[3])*1000;useEffect(()=>{if(!running)return;end.current=Date.now()+remaining;const id=setInterval(()=>{const r=Math.max(0,end.current-Date.now());setRemaining(r);if(r<=0)setRunning(false)},200);return()=>clearInterval(id)},[running]);function change(i:number,v:string){const next=[...parts];next[i]=Math.max(0,Number(v)||0);setParts(next);if(!running)setRemaining(((next[0]*86400)+(next[1]*3600)+(next[2]*60)+next[3])*1000)}return <section className="runner interactive-runner"><div className="time-inputs">{[u.days,u.hours,u.minutes,u.seconds].map((label,i)=><label className="option-field" key={label}><span>{label}</span><input type="number" min="0" value={parts[i]} onChange={e=>change(i,e.target.value)}/></label>)}</div><div className="time-display">{fmt(remaining)}</div><div className="runner-actions center-actions"><button className="primary" onClick={()=>{if(!running){if(remaining<=0)setRemaining(total());setRunning(true)}}}>{u.start}</button><button onClick={()=>setRunning(false)}>{u.pause}</button><button onClick={()=>{setRunning(false);setRemaining(total())}}>{u.reset}</button></div></section>}

function Stopwatch({locale}:{locale:Locale}){const u=ui[locale],[elapsed,setElapsed]=useState(0),[running,setRunning]=useState(false),start=useRef(0),base=useRef(0);useEffect(()=>{if(!running)return;start.current=performance.now();const id=setInterval(()=>setElapsed(base.current+performance.now()-start.current),30);return()=>clearInterval(id)},[running]);return <section className="runner interactive-runner"><div className="time-display stopwatch-display">{fmt(elapsed)}<small>.{String(Math.floor(elapsed%1000)).padStart(3,'0')}</small></div><div className="runner-actions center-actions"><button className="primary" onClick={()=>{if(!running){base.current=elapsed;setRunning(true)}}}>{u.start}</button><button onClick={()=>{base.current=elapsed;setRunning(false)}}>{u.pause}</button><button onClick={()=>{setRunning(false);base.current=0;setElapsed(0)}}>{u.reset}</button></div></section>}

function ScreenRecorder({locale}:{locale:Locale}){const u=ui[locale],[recording,setRecording]=useState(false),[download,setDownload]=useState(''),[error,setError]=useState(''),rec=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),chunks=useRef<Blob[]>([]);async function begin(){setError('');if(download)URL.revokeObjectURL(download);setDownload('');try{const s=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});stream.current=s;const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(x=>MediaRecorder.isTypeSupported(x));const r=new MediaRecorder(s,mime?{mimeType:mime}:undefined);rec.current=r;chunks.current=[];r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=()=>{const b=new Blob(chunks.current,{type:r.mimeType||'video/webm'});setDownload(URL.createObjectURL(b));s.getTracks().forEach(t=>t.stop());setRecording(false)};s.getVideoTracks()[0]?.addEventListener('ended',()=>{if(r.state!=='inactive')r.stop()});r.start(1000);setRecording(true)}catch(e){setError(e instanceof Error?e.message:'Unable to start screen recording')}}function stop(){if(rec.current&&rec.current.state!=='inactive')rec.current.stop();stream.current?.getTracks().forEach(t=>t.stop())}return <section className="runner interactive-runner"><div className={`record-status ${recording?'active':''}`}><span/>{recording?'REC':'READY'}</div><div className="runner-actions center-actions">{!recording?<button className="primary" onClick={begin}>{u.record}</button>:<button className="primary danger-action" onClick={stop}>{u.stop}</button>}</div>{error&&<div className="result-summary error-text">{error}</div>}{download&&<div className="asset-result result-after"><video controls src={download}/><a className="download-button" href={download} download="controols-screen-recording.webm">↓ {u.download}</a></div>}</section>}

export default function PineInteractiveRunner({tool,locale}:{tool:Tool;locale:Locale}){if(tool.slug==='timer')return <Timer locale={locale}/>;if(tool.slug==='stopwatch')return <Stopwatch locale={locale}/>;return <ScreenRecorder locale={locale}/>}
