'use client';
import { useState } from 'react';
import QRCode from 'qrcode';
import JsBarcode from 'jsbarcode';
import { BrowserMultiFormatReader, BrowserQRCodeReader } from '@zxing/browser';
import type { Locale, Tool } from '@/src/data/catalog';
import { copy } from '@/src/i18n';

const T:Record<Locale,Record<string,string>>={
 en:{choose:'Choose image',drag:'or drag and drop here',url:'URL',network:'Network name',password:'Password',security:'Security',email:'Email',phone:'Phone',message:'Message',latitude:'Latitude',longitude:'Longitude',name:'Name',title:'Title',start:'Start',end:'End',location:'Location',text:'Text / value',download:'Download'},
 pt:{choose:'Escolher imagem',drag:'ou arraste e solte aqui',url:'URL',network:'Nome da rede',password:'Senha',security:'Segurança',email:'E-mail',phone:'Telefone',message:'Mensagem',latitude:'Latitude',longitude:'Longitude',name:'Nome',title:'Título',start:'Início',end:'Fim',location:'Local',text:'Texto / valor',download:'Baixar'},
 es:{choose:'Elegir imagen',drag:'o arrastra y suelta aquí',url:'URL',network:'Nombre de red',password:'Contraseña',security:'Seguridad',email:'Correo',phone:'Teléfono',message:'Mensaje',latitude:'Latitud',longitude:'Longitud',name:'Nombre',title:'Título',start:'Inicio',end:'Fin',location:'Lugar',text:'Texto / valor',download:'Descargar'},
 zh:{choose:'选择图片',drag:'或拖放到这里',url:'URL',network:'网络名称',password:'密码',security:'安全类型',email:'邮箱',phone:'电话',message:'消息',latitude:'纬度',longitude:'经度',name:'姓名',title:'标题',start:'开始',end:'结束',location:'地点',text:'文本 / 值',download:'下载'},
 hi:{choose:'चित्र चुनें',drag:'या यहाँ खींचकर छोड़ें',url:'URL',network:'नेटवर्क नाम',password:'पासवर्ड',security:'सुरक्षा',email:'ईमेल',phone:'फोन',message:'संदेश',latitude:'अक्षांश',longitude:'देशांतर',name:'नाम',title:'शीर्षक',start:'आरंभ',end:'अंत',location:'स्थान',text:'टेक्स्ट / मान',download:'डाउनलोड'}
};
const barcodeFormats:Record<string,string>={'text-barcode-code128':'CODE128','ean13-barcode-generator':'EAN13','ean8-barcode-generator':'EAN8','upca-barcode-generator':'UPC','code39-barcode-generator':'CODE39','itf-barcode-generator':'ITF14','codabar-generator':'codabar'};
type V=Record<string,string>;
function payload(slug:string,v:V){switch(slug){case'url-qr-code':return/^https?:\/\//i.test(v.url)?v.url:`https://${v.url}`;case'wifi-qr-code':return`WIFI:T:${v.security||'WPA'};S:${v.network};P:${v.password};;`;case'email-qr-code':return`mailto:${v.email}`;case'phone-qr-code':return`tel:${v.phone}`;case'sms-qr-code':return`SMSTO:${v.phone}:${v.message||''}`;case'whatsapp-qr-code':return`https://wa.me/${(v.phone||'').replace(/\D/g,'')}${v.message?`?text=${encodeURIComponent(v.message)}`:''}`;case'location-qr-code':return`geo:${v.latitude},${v.longitude}`;case'contact-vcard-qr-code':return`BEGIN:VCARD\nVERSION:3.0\nFN:${v.name}\nTEL:${v.phone}\nEMAIL:${v.email}\nEND:VCARD`;case'event-qr-code':return`BEGIN:VEVENT\nSUMMARY:${v.title}\nDTSTART:${(v.start||'').replace(/[-:]/g,'')}\nDTEND:${(v.end||'').replace(/[-:]/g,'')}\nLOCATION:${v.location||''}\nEND:VEVENT`;default:return v.text||''}}
function fields(slug:string,locale:Locale){const l=T[locale],F=(key:string,type='text',required=true,extra:Record<string,unknown>={})=><label className="smart-field" key={key}><span>{l[key]||key}</span><input name={key} type={type} required={required} {...extra}/></label>;if(slug==='url-qr-code')return[F('url','url')];if(slug==='wifi-qr-code')return[F('network'),F('password','password'),<label className="smart-field" key="security"><span>{l.security}</span><select name="security" defaultValue="WPA"><option>WPA</option><option>WEP</option><option value="nopass">Open</option></select></label>];if(slug==='email-qr-code')return[F('email','email')];if(slug==='phone-qr-code')return[F('phone','tel')];if(['sms-qr-code','whatsapp-qr-code'].includes(slug))return[F('phone','tel'),<label className="smart-field smart-field-wide" key="message"><span>{l.message}</span><textarea name="message"/></label>];if(slug==='location-qr-code')return[F('latitude','number',true,{min:-90,max:90,step:'0.000001'}),F('longitude','number',true,{min:-180,max:180,step:'0.000001'})];if(slug==='contact-vcard-qr-code')return[F('name'),F('phone','tel'),F('email','email')];if(slug==='event-qr-code')return[F('title'),F('start','datetime-local'),F('end','datetime-local'),F('location','text',false)];const numeric=slug.startsWith('ean')||slug==='upca-barcode-generator'||slug==='itf-barcode-generator';return[<label className="smart-field smart-field-wide" key="text"><span>{l.text}</span>{barcodeFormats[slug]?<input name="text" type="text" required inputMode={numeric?'numeric':undefined} pattern={numeric?'[0-9]+':undefined}/>:<textarea name="text" required/>}</label>]}
export default function StructuredQRToolRunner({tool,locale}:{tool:Tool;locale:Locale}){const t=copy[locale],l=T[locale],[result,setResult]=useState(''),[image,setImage]=useState(''),[busy,setBusy]=useState(false);const reader=tool.slug==='qr-code-reader'||tool.slug==='barcode-reader';async function read(file:File){setBusy(true);setResult('');const url=URL.createObjectURL(file);setImage(url);try{const r=tool.slug==='qr-code-reader'?new BrowserQRCodeReader():new BrowserMultiFormatReader();setResult((await r.decodeFromImageUrl(url)).getText())}catch(e){setResult(e instanceof Error?e.message:'Code not found')}finally{setBusy(false)}}async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setResult('');setImage('');const fd=new FormData(e.currentTarget),v=Object.fromEntries([...fd.entries()].map(([k,x])=>[k,String(x)]));try{const data=payload(tool.slug,v);if(barcodeFormats[tool.slug]){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');JsBarcode(svg,data,{format:barcodeFormats[tool.slug],displayValue:true,margin:24,height:100});const text=new XMLSerializer().serializeToString(svg);setImage(`data:image/svg+xml;charset=utf-8,${encodeURIComponent(text)}`);setResult(data)}else if(tool.slug==='qr-code-svg-generator'){const svg=await QRCode.toString(data,{type:'svg',margin:2,width:640,errorCorrectionLevel:'M'});setImage(`data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`);setResult(data)}else{setImage(await QRCode.toDataURL(data,{width:640,margin:2,errorCorrectionLevel:'M'}));setResult(data)}}catch(e){setResult(e instanceof Error?e.message:'Invalid value')}setBusy(false)}return <section className="runner asset-runner">{reader?<div className="asset-controls"><label className="drop-zone"><input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&read(e.target.files[0])}/><strong>{busy?'…':l.choose}</strong><span>{l.drag}</span></label></div>:<form className="asset-controls" onSubmit={submit}><div className="smart-fields">{fields(tool.slug,locale)}</div><button className="primary" disabled={busy}>{busy?'…':t.run}</button></form>}{(image||result)&&<div className="asset-result">{image&&<img src={image} alt="Result"/>}{result&&<div className="result-summary">{result}</div>}{image&&!reader&&<a className="download-button" href={image} download={`controols-${tool.slug}.${tool.slug.includes('qr')&&!tool.slug.includes('svg')?'png':'svg'}`}>{l.download}</a>}</div>}</section>}
