'use client';

import { useState } from 'react';
import type { Locale, Tool } from '@/src/data/catalog';
import { copy } from '@/src/i18n';

type Loaded={img:HTMLImageElement;width:number;height:number};type Dl={name:string;url:string};
function C(w:number,h:number){const c=document.createElement('canvas');c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));return c}
async function load(file:File):Promise<Loaded>{const url=URL.createObjectURL(file);return await new Promise((res,rej)=>{const img=new Image();img.onload=()=>{res({img,width:img.naturalWidth,height:img.naturalHeight});URL.revokeObjectURL(url)};img.onerror=()=>{URL.revokeObjectURL(url);rej(new Error('Unable to decode image'))};img.src=url})}
function draw(src:Loaded,w=src.width,h=src.height){const c=C(w,h);c.getContext('2d')!.drawImage(src.img,0,0,w,h);return c}
function toBlob(c:HTMLCanvasElement,type='image/png'){return new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('Export failed')),type,.92))}
function clamp(n:number,a:number,b:number){return Math.max(a,Math.min(b,n))}
function mapPixels(c:HTMLCanvasElement,fn:(r:number,g:number,b:number,a:number)=>[number,number,number,number]){const x=c.getContext('2d')!,d=x.getImageData(0,0,c.width,c.height);for(let i=0;i<d.data.length;i+=4){const p=fn(d.data[i],d.data[i+1],d.data[i+2],d.data[i+3]);d.data[i]=clamp(p[0],0,255);d.data[i+1]=clamp(p[1],0,255);d.data[i+2]=clamp(p[2],0,255);d.data[i+3]=clamp(p[3],0,255)}x.putImageData(d,0,0)}
function conv(c:HTMLCanvasElement,k:number[],div=1,bias=0){const x=c.getContext('2d')!,src=x.getImageData(0,0,c.width,c.height),out=x.createImageData(c.width,c.height),side=Math.sqrt(k.length)|0,half=side>>1;for(let y=0;y<c.height;y++)for(let xx=0;xx<c.width;xx++){const oi=(y*c.width+xx)*4;for(let ch=0;ch<3;ch++){let sum=0;for(let ky=0;ky<side;ky++)for(let kx=0;kx<side;kx++){const px=clamp(xx+kx-half,0,c.width-1),py=clamp(y+ky-half,0,c.height-1);sum+=src.data[(py*c.width+px)*4+ch]*k[ky*side+kx]}out.data[oi+ch]=clamp(sum/div+bias,0,255)}out.data[oi+3]=src.data[oi+3]}x.putImageData(out,0,0)}
function hex(h:string){const s=h.replace('#','');return[parseInt(s.slice(0,2),16)||0,parseInt(s.slice(2,4),16)||0,parseInt(s.slice(4,6),16)||0]}
function palette(c:HTMLCanvasElement,count:number){const d=c.getContext('2d')!.getImageData(0,0,c.width,c.height).data,bins=new Map<string,number>(),step=Math.max(1,Math.floor(Math.sqrt(c.width*c.height/40000)));for(let y=0;y<c.height;y+=step)for(let x=0;x<c.width;x+=step){const i=(y*c.width+x)*4,key=[d[i],d[i+1],d[i+2]].map(v=>Math.min(255,Math.round(v/32)*32).toString(16).padStart(2,'0')).join('').toUpperCase();bins.set(key,(bins.get(key)||0)+1)}return[...bins].sort((a,b)=>b[1]-a[1]).slice(0,count).map(([v])=>`#${v}`)}
function histogram(c:HTMLCanvasElement){const d=c.getContext('2d')!.getImageData(0,0,c.width,c.height).data,h=new Array(256).fill(0);for(let i=0;i<d.length;i+=4)h[Math.round(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2])]++;return h}
function equalize(c:HTMLCanvasElement){const x=c.getContext('2d')!,d=x.getImageData(0,0,c.width,c.height),h=histogram(c),cdf:number[]=[],total=c.width*c.height;let sum=0;for(let i=0;i<256;i++){sum+=h[i];cdf[i]=sum/total*255}for(let i=0;i<d.data.length;i+=4){const y=Math.round(.2126*d.data[i]+.7152*d.data[i+1]+.0722*d.data[i+2]),target=cdf[y],scale=y?target/y:1;d.data[i]=clamp(d.data[i]*scale,0,255);d.data[i+1]=clamp(d.data[i+1]*scale,0,255);d.data[i+2]=clamp(d.data[i+2]*scale,0,255)}x.putImageData(d,0,0)}
function randomBitmap(w:number,h:number){const c=C(w,h),x=c.getContext('2d')!,d=x.createImageData(w,h);for(let o=0;o<d.data.length;o+=65536)crypto.getRandomValues(d.data.subarray(o,Math.min(d.data.length,o+65536)));for(let i=3;i<d.data.length;i+=4)d.data[i]=255;x.putImageData(d,0,0);return c}
function normalize(slug:string){let s=slug.replace(/^bulk-/,'');const m:Record<string,string>={'change-brightness':'brightness-contrast','change-contrast':'brightness-contrast','change-saturation':'adjust-hsl','grayscale-image':'grayscale-image','invert-colors':'invert-image-colors','pixelate-effect':'censor-photo','sepia-effect':'sepia-image','sharpen-image':'sharpen-image','blur-image':'blur-image','flip-image':'flip-image-horizontal','resize-image':'resize-image','crop-image':'clip-image','get-colors-from-image':'get-colors-from-image'};return m[s]||s}
const U:Record<Locale,Record<string,string>>={
 en:{choose:'Choose image',many:'Choose images',two:'Choose 2 images',drag:'or drag and drop here',apply:'Apply',download:'Download',amount:'Amount',brightness:'Brightness',contrast:'Contrast',saturation:'Saturation',gamma:'Gamma',hue:'Hue',noise:'Noise',red:'Red channel',green:'Green channel',blue:'Blue channel',opacity:'Opacity',color:'Color',color2:'Second color',threshold:'Threshold',levels:'Levels',radius:'Radius',rotation:'Rotation',blur:'Blur',width:'Width',height:'Height',x:'X position',y:'Y position',rows:'Rows',columns:'Columns',count:'Number of colors',filter:'Filter',channel:'Channel',tolerance:'Tolerance'},
 pt:{choose:'Escolher imagem',many:'Escolher imagens',two:'Escolher 2 imagens',drag:'ou arraste e solte aqui',apply:'Aplicar',download:'Baixar',amount:'Intensidade',brightness:'Brilho',contrast:'Contraste',saturation:'Saturação',gamma:'Gamma',hue:'Matiz',noise:'Ruído',red:'Canal vermelho',green:'Canal verde',blue:'Canal azul',opacity:'Opacidade',color:'Cor',color2:'Segunda cor',threshold:'Limite',levels:'Níveis',radius:'Raio',rotation:'Rotação',blur:'Desfoque',width:'Largura',height:'Altura',x:'Posição X',y:'Posição Y',rows:'Linhas',columns:'Colunas',count:'Quantidade de cores',filter:'Filtro',channel:'Canal',tolerance:'Tolerância'},
 es:{choose:'Elegir imagen',many:'Elegir imágenes',two:'Elegir 2 imágenes',drag:'o arrastra y suelta aquí',apply:'Aplicar',download:'Descargar',amount:'Intensidad',brightness:'Brillo',contrast:'Contraste',saturation:'Saturación',gamma:'Gamma',hue:'Matiz',noise:'Ruido',red:'Canal rojo',green:'Canal verde',blue:'Canal azul',opacity:'Opacidad',color:'Color',color2:'Segundo color',threshold:'Umbral',levels:'Niveles',radius:'Radio',rotation:'Rotación',blur:'Desenfoque',width:'Ancho',height:'Alto',x:'Posición X',y:'Posición Y',rows:'Filas',columns:'Columnas',count:'Cantidad de colores',filter:'Filtro',channel:'Canal',tolerance:'Tolerancia'},
 zh:{choose:'选择图片',many:'选择多张图片',two:'选择 2 张图片',drag:'或拖放到这里',apply:'应用',download:'下载',amount:'强度',brightness:'亮度',contrast:'对比度',saturation:'饱和度',gamma:'Gamma',hue:'色相',noise:'噪点',red:'红色通道',green:'绿色通道',blue:'蓝色通道',opacity:'透明度',color:'颜色',color2:'第二颜色',threshold:'阈值',levels:'层级',radius:'半径',rotation:'旋转',blur:'模糊',width:'宽度',height:'高度',x:'X 位置',y:'Y 位置',rows:'行',columns:'列',count:'颜色数量',filter:'滤镜',channel:'通道',tolerance:'容差'},
 hi:{choose:'चित्र चुनें',many:'चित्र चुनें',two:'2 चित्र चुनें',drag:'या यहाँ खींचकर छोड़ें',apply:'लागू करें',download:'डाउनलोड',amount:'मात्रा',brightness:'चमक',contrast:'कॉन्ट्रास्ट',saturation:'सैचुरेशन',gamma:'Gamma',hue:'ह्यू',noise:'नॉइज़',red:'लाल चैनल',green:'हरा चैनल',blue:'नीला चैनल',opacity:'अपारदर्शिता',color:'रंग',color2:'दूसरा रंग',threshold:'सीमा',levels:'स्तर',radius:'त्रिज्या',rotation:'घुमाव',blur:'ब्लर',width:'चौड़ाई',height:'ऊँचाई',x:'X स्थिति',y:'Y स्थिति',rows:'पंक्तियाँ',columns:'कॉलम',count:'रंगों की संख्या',filter:'फ़िल्टर',channel:'चैनल',tolerance:'सहनशीलता'}
};
const generators=new Set(['random-bitmap-generator','image-gradient-generator','image-radial-gradient-generator']);
export default function StructuredPineImageToolRunner({tool,locale}:{tool:Tool;locale:Locale}){
 const t=copy[locale],u=U[locale],bulk=tool.slug.startsWith('bulk-'),base=normalize(tool.slug),generator=generators.has(base),screenshot=base==='take-screenshot',[files,setFiles]=useState<File[]>([]),[v,setV]=useState<Record<string,string>>({amount:'20',brightness:'110',contrast:'110',saturation:'110',gamma:'1.2',hue:'30',noise:'25',red:'100',green:'100',blue:'100',opacity:'.65',color:'#22c983',color2:'#111419',threshold:'128',levels:'5',radius:'24',rotation:'90',blur:'10',width:'1200',height:'800',x:'0',y:'0',rows:'2',columns:'2',count:'8',filter:'sepia',channel:'rgb',tolerance:'35'}),[downloads,setDownloads]=useState<Dl[]>([]),[output,setOutput]=useState(''),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false);const multi=bulk||['merge-images','overlay-images'].includes(base),set=(k:string,x:string)=>setV(a=>({...a,[k]:x}));function clear(){downloads.forEach(d=>URL.revokeObjectURL(d.url));setDownloads([]);if(preview)URL.revokeObjectURL(preview);setPreview('');setOutput('')}
 async function capture(){setBusy(true);clear();try{const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false}),video=document.createElement('video');video.srcObject=stream;await video.play();await new Promise(r=>setTimeout(r,200));const c=C(video.videoWidth,video.videoHeight);c.getContext('2d')!.drawImage(video,0,0);stream.getTracks().forEach(x=>x.stop());const b=await toBlob(c),d={name:'controols-screenshot.png',url:URL.createObjectURL(b)};setDownloads([d]);setPreview(d.url);setOutput(`${c.width} × ${c.height}px`)}catch(e){setOutput(e instanceof Error?e.message:'Unable to capture screen')}finally{setBusy(false)}}
 async function transform(file:File,index:number):Promise<Dl[]>{const src=await load(file);let c=draw(src);const amount=Number(v.amount)||20;
  if(['darken-image','lighten-image','change-vibrance','change-exposure','adjust-hue','blur-image','grayscale-image','sepia-image','invert-image-colors','brightness-contrast','adjust-hsl','special-filters'].includes(base)){c=C(src.width,src.height);const x=c.getContext('2d')!;let f='none';if(base==='darken-image')f=`brightness(${Math.max(0,100-amount)}%)`;if(base==='lighten-image')f=`brightness(${100+amount}%)`;if(base==='change-vibrance')f=`saturate(${100+amount}%) contrast(105%)`;if(base==='change-exposure')f=`brightness(${100+amount}%)`;if(base==='adjust-hue')f=`hue-rotate(${Number(v.hue)||30}deg)`;if(base==='blur-image')f=`blur(${Number(v.blur)||6}px)`;if(base==='grayscale-image')f='grayscale(1)';if(base==='sepia-image')f='sepia(1)';if(base==='invert-image-colors')f='invert(1)';if(base==='brightness-contrast')f=`brightness(${Number(v.brightness)||110}%) contrast(${Number(v.contrast)||110}%)`;if(base==='adjust-hsl')f=`hue-rotate(${Number(v.hue)||0}deg) saturate(${Number(v.saturation)||100}%) brightness(${Number(v.brightness)||100}%)`;if(base==='special-filters')f=v.filter==='grayscale'?'grayscale(1)':v.filter==='invert'?'invert(1)':'sepia(1)';x.filter=f;x.drawImage(src.img,0,0)}
  else if(base==='adjust-gamma'){const g=Math.max(.1,Number(v.gamma)||1.2);mapPixels(c,(r,gg,b,a)=>[255*Math.pow(r/255,1/g),255*Math.pow(gg/255,1/g),255*Math.pow(b/255,1/g),a])}
  else if(base==='add-noise'){const amp=Number(v.noise)||25;mapPixels(c,(r,g,b,a)=>{const z=(Math.random()-.5)*2*amp;return[r+z,g+z,b+z,a]})}
  else if(base==='adjust-channels'||base==='rgb-channels'){const rr=Number(v.red)||100,gg=Number(v.green)||100,bb=Number(v.blue)||100;mapPixels(c,(r,g,b,a)=>[r*rr/100,g*gg/100,b*bb/100,a])}
  else if(base==='vignette-effect'){const x=c.getContext('2d')!,g=x.createRadialGradient(c.width/2,c.height/2,Math.min(c.width,c.height)*.2,c.width/2,c.height/2,Math.max(c.width,c.height)*.7);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,`rgba(0,0,0,${clamp(Number(v.opacity)||.65,0,1)})`);x.fillStyle=g;x.fillRect(0,0,c.width,c.height)}
  else if(base==='colorize-image'||base==='duotone-effect'){const a=hex(v.color),b=hex(v.color2);mapPixels(c,(r,g,bl,alpha)=>{const y=(r+g+bl)/(3*255);return base==='duotone-effect'?[a[0]*(1-y)+b[0]*y,a[1]*(1-y)+b[1]*y,a[2]*(1-y)+b[2]*y,alpha]:[(r+a[0])/2,(g+a[1])/2,(bl+a[2])/2,alpha]})}
  else if(base==='threshold-black-white'){const th=Number(v.threshold)||128;mapPixels(c,(r,g,b,a)=>{const y=.2126*r+.7152*g+.0722*b,z=y>=th?255:0;return[z,z,z,a]})}
  else if(base==='posterize-effect'){const levels=clamp(Number(v.levels)||5,2,16),step=255/(levels-1);mapPixels(c,(r,g,b,a)=>[Math.round(r/step)*step,Math.round(g/step)*step,Math.round(b/step)*step,a])}
  else if(base==='solarize-effect'){const th=Number(v.threshold)||128;mapPixels(c,(r,g,b,a)=>[r>th?255-r:r,g>th?255-g:g,b>th?255-b:b,a])}
  else if(base==='edge-detection')conv(c,[-1,-1,-1,-1,8,-1,-1,-1,-1]);else if(base==='edge-enhancement')conv(c,[0,-1,0,-1,9,-1,0,-1,0]);else if(base==='emboss-effect')conv(c,[-2,-1,0,-1,1,1,0,1,2],1,128);else if(base==='color-emboss-effect')conv(c,[-2,-1,0,-1,1,1,0,1,2],1,96);else if(base==='sharpen-image')conv(c,[0,-1,0,-1,5,-1,0,-1,0]);
  else if(base==='remove-noise'){const x=c.getContext('2d')!,srcd=x.getImageData(0,0,c.width,c.height),out=x.createImageData(c.width,c.height);for(let y=0;y<c.height;y++)for(let xx=0;xx<c.width;xx++){for(let ch=0;ch<3;ch++){let s=0,k=0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const px=clamp(xx+dx,0,c.width-1),py=clamp(y+dy,0,c.height-1);s+=srcd.data[(py*c.width+px)*4+ch];k++}out.data[(y*c.width+xx)*4+ch]=s/k}out.data[(y*c.width+xx)*4+3]=srcd.data[(y*c.width+xx)*4+3]}x.putImageData(out,0,0)}
  else if(base==='equalize-image'||base==='equalize-image-area')equalize(c);
  else if(base==='censor-photo'){const s=Math.max(2,Number(v.amount)||14),sm=C(Math.ceil(src.width/s),Math.ceil(src.height/s));sm.getContext('2d')!.drawImage(src.img,0,0,sm.width,sm.height);c=C(src.width,src.height);const x=c.getContext('2d')!;x.imageSmoothingEnabled=false;x.drawImage(sm,0,0,c.width,c.height)}
  else if(base==='round-corners-image'){const r=clamp(Number(v.radius)||24,0,Math.min(src.width,src.height)/2),out=C(src.width,src.height),x=out.getContext('2d')!;x.beginPath();x.roundRect(0,0,out.width,out.height,r);x.clip();x.drawImage(src.img,0,0);c=out}
  else if(base==='rotate-image'){const deg=Number(v.rotation)||90,rad=deg*Math.PI/180,s=Math.abs(Math.sin(rad)),co=Math.abs(Math.cos(rad)),w=src.width*co+src.height*s,h=src.width*s+src.height*co;c=C(w,h);const x=c.getContext('2d')!;x.translate(w/2,h/2);x.rotate(rad);x.drawImage(src.img,-src.width/2,-src.height/2)}
  else if(base==='flip-image-horizontal'){c=C(src.width,src.height);const x=c.getContext('2d')!;x.translate(src.width,0);x.scale(-1,1);x.drawImage(src.img,0,0)}
  else if(base==='resize-image')c=draw(src,Number(v.width)||src.width,Number(v.height)||src.height);
  else if(base==='clip-image'){const x0=Number(v.x)||0,y0=Number(v.y)||0,w=Number(v.width)||src.width,h=Number(v.height)||src.height;c=C(w,h);c.getContext('2d')!.drawImage(src.img,x0,y0,w,h,0,0,w,h)}
  else if(base==='glow-effect'){const x=c.getContext('2d')!;x.save();x.globalCompositeOperation='screen';x.filter=`blur(${Number(v.blur)||8}px)`;x.globalAlpha=.6;x.drawImage(src.img,0,0);x.restore()}
  else if(base==='tilt-shift-effect'||base==='blurred-frame-image-generator'){const blur=Number(v.blur)||10,tmp=C(c.width,c.height),tx=tmp.getContext('2d')!;tx.filter=`blur(${blur}px)`;tx.drawImage(src.img,0,0);const x=c.getContext('2d')!;x.clearRect(0,0,c.width,c.height);x.drawImage(tmp,0,0);if(base==='tilt-shift-effect'){const h=c.height*.35;x.save();x.beginPath();x.rect(0,(c.height-h)/2,c.width,h);x.clip();x.filter='none';x.drawImage(src.img,0,0);x.restore()}else{x.save();x.beginPath();x.rect(c.width*.08,c.height*.08,c.width*.84,c.height*.84);x.clip();x.filter='none';x.drawImage(src.img,0,0);x.restore()}}
  else if(base==='remove-background'){const target=hex(v.color),tol=Number(v.tolerance)||35;mapPixels(c,(r,g,b,a)=>[r,g,b,Math.hypot(r-target[0],g-target[1],b-target[2])<=tol?0:a])}
  else if(base==='svg-converter-viewer'){c=draw(src)}
  if(base==='get-colors-from-image'){setOutput(palette(c,clamp(Number(v.count)||8,2,32)).join('\n'));return[]}
  if(base==='image-histogram'){setOutput(JSON.stringify(histogram(c),null,2));return[]}
  if(base==='split-image'){const rows=clamp(Number(v.rows)||2,1,20),cols=clamp(Number(v.columns)||2,1,20),w=Math.floor(c.width/cols),h=Math.floor(c.height/rows),ds:Dl[]=[];for(let ry=0;ry<rows;ry++)for(let cx=0;cx<cols;cx++){const part=C(w,h);part.getContext('2d')!.drawImage(c,cx*w,ry*h,w,h,0,0,w,h);const b=await toBlob(part);ds.push({name:`controols-${tool.slug}-${ry+1}-${cx+1}.png`,url:URL.createObjectURL(b)})}return ds}
  const b=await toBlob(c),d={name:`controols-${tool.slug}-${index+1}.png`,url:URL.createObjectURL(b)};return[d]}
 async function process(){setBusy(true);clear();try{if(generator){let c:HTMLCanvasElement;const w=clamp(Number(v.width)||1200,1,8000),h=clamp(Number(v.height)||800,1,8000);if(base==='random-bitmap-generator')c=randomBitmap(w,h);else{c=C(w,h);const x=c.getContext('2d')!,a=v.color||'#22c983',b=v.color2||'#111419',g=base==='image-radial-gradient-generator'?x.createRadialGradient(w/2,h/2,0,w/2,h/2,Math.max(w,h)/2):x.createLinearGradient(0,0,w,h);g.addColorStop(0,a);g.addColorStop(1,b);x.fillStyle=g;x.fillRect(0,0,w,h)}const b=await toBlob(c),d={name:`controols-${base}.png`,url:URL.createObjectURL(b)};setDownloads([d]);setPreview(d.url);setOutput(`${w} × ${h}px`);return}if(['merge-images','overlay-images'].includes(base)){if(files.length<2)throw new Error('Choose 2 images.');const a=await load(files[0]),b=await load(files[1]),w=Math.max(a.width,b.width),h=Math.max(a.height,b.height),c=C(w,h),x=c.getContext('2d')!;x.drawImage(a.img,0,0);x.globalAlpha=clamp(Number(v.opacity)||.65,0,1);x.drawImage(b.img,0,0,w,h);x.globalAlpha=1;const bb=await toBlob(c),d={name:`controols-${base}.png`,url:URL.createObjectURL(bb)};setDownloads([d]);setPreview(d.url);setOutput(`${w} × ${h}px`);return}if(!files.length)throw new Error('Choose an image first.');const ds:Dl[]=[];for(let i=0;i<files.length;i++)ds.push(...await transform(files[i],i));setDownloads(ds);if(ds[0])setPreview(ds[0].url);if(!output)setOutput(`${files.length} image${files.length===1?'':'s'} processed`)}catch(e){setOutput(`Error: ${e instanceof Error?e.message:'Unable to process image'}`)}finally{setBusy(false)}}
 const controls=controlKeys(base);return <section className="runner asset-runner"><div className="asset-controls">{screenshot?<button className="primary big-action" onClick={capture} disabled={busy}>{busy?'…':t.run}</button>:!generator&&<label className="drop-zone"><input type="file" accept="image/*,.svg" multiple={multi} onChange={e=>{clear();setFiles(Array.from(e.target.files||[]))}}/><strong>{multi?(files.length?`${files.length} · ${u.many}`:u.many):u.choose}</strong><span>{files.length?files.map(f=>f.name).join('\n'):u.drag}</span></label>}{!screenshot&&(generator||files.length>0)&&controls.length>0&&<div className="smart-fields">{controls.map(k=><Control key={k} k={k} v={v} set={set} u={u}/>)}</div>}{!screenshot&&(generator||files.length>0)&&<button className="primary big-action" onClick={process} disabled={busy}>{busy?'…':u.apply}</button>}</div>{(output||downloads.length>0)&&<div className="asset-result">{preview&&<img src={preview} alt="Preview"/>}{output&&<pre className="result-text">{output}</pre>}{downloads.length>0&&<div className="download-list">{downloads.map((d,i)=><a className="download-button" href={d.url} download={d.name} key={i}>↓ {u.download}{downloads.length>1?` ${i+1}`:''}</a>)}</div>}</div>}</section>}
function controlKeys(base:string){const m:Record<string,string[]>={
 'darken-image':['amount'],'lighten-image':['amount'],'change-vibrance':['amount'],'change-exposure':['amount'],'adjust-gamma':['gamma'],'add-noise':['noise'],'adjust-hue':['hue'],'blur-image':['blur'],'special-filters':['filter'],'adjust-channels':['red','green','blue'],'rgb-channels':['red','green','blue'],'vignette-effect':['opacity'],'colorize-image':['color'],'duotone-effect':['color','color2'],'threshold-black-white':['threshold'],'posterize-effect':['levels'],'solarize-effect':['threshold'],'round-corners-image':['radius'],'rotate-image':['rotation'],'brightness-contrast':['brightness','contrast'],'adjust-hsl':['hue','saturation','brightness'],'glow-effect':['blur'],'censor-photo':['amount'],'overlay-images':['opacity'],'merge-images':['opacity'],'get-colors-from-image':['count'],'split-image':['rows','columns'],'equalize-image-area':['x','y','width','height'],'image-gradient-generator':['width','height','color','color2'],'image-radial-gradient-generator':['width','height','color','color2'],'random-bitmap-generator':['width','height'],'blurred-frame-image-generator':['blur'],'remove-background':['color','tolerance'],'resize-image':['width','height'],'clip-image':['x','y','width','height'],'tilt-shift-effect':['blur']};return m[base]||[]}
function Control({k,v,set,u}:{k:string;v:Record<string,string>;set:(k:string,x:string)=>void;u:Record<string,string>}){if(k==='color'||k==='color2')return <label className="smart-field"><span>{u[k]}</span><div className="color-control"><input type="color" value={v[k]} onChange={e=>set(k,e.target.value)}/><output>{v[k]}</output></div></label>;if(k==='filter')return <label className="smart-field"><span>{u.filter}</span><select value={v.filter} onChange={e=>set('filter',e.target.value)}><option value="sepia">Sepia</option><option value="grayscale">Grayscale</option><option value="invert">Invert</option></select></label>;if(k==='rotation')return <label className="smart-field"><span>{u.rotation}</span><select value={v.rotation} onChange={e=>set('rotation',e.target.value)}><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></label>;const ranges:Record<string,[number,number,number]>={opacity:[0,1,.05],gamma:[.1,5,.05],threshold:[0,255,1],levels:[2,16,1],radius:[0,1000,1],hue:[-360,360,1],brightness:[0,300,1],contrast:[0,300,1],saturation:[0,300,1],red:[0,300,1],green:[0,300,1],blue:[0,300,1],amount:[0,300,1],noise:[0,255,1],blur:[0,100,1],tolerance:[0,442,1],width:[1,8000,1],height:[1,8000,1],x:[0,8000,1],y:[0,8000,1],rows:[1,20,1],columns:[1,20,1],count:[2,32,1]};const r=ranges[k]||[-999999,999999,.01];return <label className="smart-field"><span>{u[k]||k}</span><input type="number" min={r[0]} max={r[1]} step={r[2]} value={v[k]} onChange={e=>set(k,e.target.value)}/></label>}
